package render_test

import (
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"flag"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/paisans-software/paisans-stack/internal/acme"
	"github.com/paisans-software/paisans-stack/internal/config"
	"github.com/paisans-software/paisans-stack/internal/kinds"
	"github.com/paisans-software/paisans-stack/internal/render"
	"github.com/paisans-software/paisans-stack/internal/secretsgen"
	"github.com/paisans-software/paisans-stack/internal/validate"
	"gopkg.in/yaml.v3"
)

var update = flag.Bool("update", false, "rewrite the golden tree from the current output")

// fixture loads the deployment every test in this file renders, and refuses to
// hand it back if the toolkit would not accept it.
//
// This is not belt and braces. Build does not validate, so for six tasks the
// fixture declared two apps under cluster placement that
// cluster-placement-without-a-cluster refuses outright, and the golden tree
// grew routing for a shape `paisans apply` would never have produced. A golden
// file is only a specification of what an operator receives if the input is
// something an operator could have written, so the check belongs here, ahead of
// every test, rather than in one test somebody might not run.
func fixture(t *testing.T) *config.Config {
	t.Helper()
	cfg, err := config.Load(filepath.Join("testdata", "deployment.yaml"))
	if err != nil {
		t.Fatalf("loading the fixture configuration: %v", err)
	}
	if refusals := validate.Check(cfg).Refusals(); len(refusals) > 0 {
		for _, f := range refusals {
			t.Errorf("the fixture is a configuration the toolkit refuses:\n%s", f)
		}
		t.FailNow()
	}
	return cfg
}

func build(t *testing.T) *render.Plan {
	t.Helper()
	cfg := fixture(t)
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatalf("loading the fixture secrets: %v", err)
	}
	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatalf("building the plan: %v", err)
	}
	return plan
}

// The golden tree is the specification of what an operator receives. A diff
// here is a change in what lands on a host, so it is reviewed rather than
// regenerated by reflex.
func TestGoldenTree(t *testing.T) {
	plan := build(t)
	golden := filepath.Join("testdata", "golden")

	if *update {
		if err := os.RemoveAll(golden); err != nil {
			t.Fatal(err)
		}
		if err := render.Write(plan, golden); err != nil {
			t.Fatal(err)
		}
		t.Log("golden tree rewritten")
		return
	}

	dir := t.TempDir()
	if err := render.Write(plan, dir); err != nil {
		t.Fatal(err)
	}
	compareTrees(t, golden, dir)
}

// Determinism is not a nicety: rendering twice must produce byte identical
// output, or a diff between two renders says nothing about what changed.
func TestRenderIsDeterministic(t *testing.T) {
	first, second := t.TempDir(), t.TempDir()
	if err := render.Write(build(t), first); err != nil {
		t.Fatal(err)
	}
	if err := render.Write(build(t), second); err != nil {
		t.Fatal(err)
	}
	compareTrees(t, first, second)
}

// A clustered app connects to the local proxy and has no Postgres of its own.
// A pinned app is pinned all the way down: its own database, at its own site.
func TestPlacementShapesTheStack(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}

	clustered, ok := files["home-a/srv/talk/compose.yaml"]
	if !ok {
		t.Fatal("the clustered app was not rendered onto an apps site")
	}
	if strings.Contains(clustered, "postgres:") {
		t.Error("a clustered app was given a Postgres service of its own")
	}
	// Each instance connects to the HAProxy on its own site, at that site's
	// mesh address. Not 127.0.0.1: inside the app's bridge networked
	// container, loopback is the container itself.
	for site, address := range map[string]string{"home-a": "10.44.0.1", "home-b": "10.44.0.2"} {
		env := files[site+"/srv/talk/.env"]
		if !strings.Contains(env, "@"+address+":5000/") {
			t.Errorf("the clustered app on %s does not connect to its own site's proxy at %s:\n%s", site, address, env)
		}
		if strings.Contains(env, "127.0.0.1") {
			t.Errorf("the clustered app on %s names a loopback address, which inside its container is the container itself:\n%s", site, env)
		}
		proxy := files[site+"/srv/infra/haproxy/haproxy.cfg"]
		if !strings.Contains(proxy, "bind "+address+":5000") {
			t.Errorf("the HAProxy on %s does not listen on the mesh address its apps are given:\n%s", site, proxy)
		}
	}

	pinned, ok := files["vm/srv/chat/compose.yaml"]
	if !ok {
		t.Fatal("the pinned app was not rendered at its site")
	}
	if !strings.Contains(pinned, "postgres:") {
		t.Error("a pinned app was not given its own Postgres")
	}
	if _, ok := files["home-a/srv/chat/compose.yaml"]; ok {
		t.Error("a pinned app was rendered somewhere other than its site")
	}
	if !strings.Contains(pinned, "/srv/chat/postgres:/var/lib/postgresql/data") {
		t.Error("a pinned stack does not use bind mounts under /srv")
	}
}

// Every published port binds the mesh address of the site it is rendered for
// and nothing else. Docker's own iptables rules bypass a host firewall such as
// ufw, so "8080:8080" on a host with a public address is reachable from the
// internet whatever the firewall says, and with no gate in front of it. The
// gateway reaches every app over the mesh, so the mesh is the only interface
// a port needs.
func TestPublishedPortsBindTheMeshAddress(t *testing.T) {
	cfg := fixture(t)
	checked := 0
	for _, f := range build(t).Files {
		if !strings.HasSuffix(f.Path, "compose.yaml") {
			continue
		}
		site := strings.SplitN(f.Path, "/", 2)[0]
		address := cfg.Sites[site].Address
		inPorts := false
		for _, line := range strings.Split(f.Content, "\n") {
			trimmed := strings.TrimSpace(line)
			if trimmed == "ports:" {
				inPorts = true
				continue
			}
			if strings.HasPrefix(trimmed, "#") {
				continue
			}
			if !strings.HasPrefix(trimmed, "- ") {
				inPorts = false
				continue
			}
			if !inPorts {
				continue
			}
			mapping := strings.Trim(strings.TrimPrefix(trimmed, "- "), `"`)
			if !strings.HasPrefix(mapping, address+":") || strings.Count(mapping, ":") != 2 {
				t.Errorf("%s publishes %q, which is not bound to %s's mesh address %s", f.Path, mapping, site, address)
			}
			checked++
		}
	}
	if checked == 0 {
		t.Fatal("no published port was found, so this test verified nothing")
	}
}

// A declared image reaches the compose file, and a service nobody declared
// takes the default its kind ships. Both halves matter: the first is what makes
// running a fork a config edit, and the second is what an adopter who never
// opens the stanza receives.
func TestDeclaredImagesWinAndDefaultsFillIn(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}

	talk := files["home-a/srv/talk/compose.yaml"]
	if !strings.Contains(talk, "image: ghcr.io/example-org/mbin:v1.10.1-fork") {
		t.Errorf("the declared image did not reach the compose file:\n%s", talk)
	}

	docs := files["home-a/srv/docs/compose.yaml"]
	fallback, ok := kinds.DefaultImage(config.KindOutline, "app")
	if !ok {
		t.Fatal("outline ships no default image")
	}
	if !strings.Contains(docs, "image: "+fallback) {
		t.Errorf("an app that declared no image did not take its kind default %q:\n%s", fallback, docs)
	}

	// A pinned app may choose its own database image; a clustered one has no
	// database service to choose for.
	chat := files["vm/srv/chat/compose.yaml"]
	if !strings.Contains(chat, "image: postgres:17-alpine") {
		t.Errorf("a pinned app's declared database image was not used:\n%s", chat)
	}
}

// Nothing the toolkit renders may carry a floating tag. A default that failed
// its own validation rule would be the toolkit refusing configuration it wrote
// itself.
func TestRenderedImagesArePinned(t *testing.T) {
	for _, f := range build(t).Files {
		if !strings.HasSuffix(f.Path, "compose.yaml") {
			continue
		}
		for _, line := range strings.Split(f.Content, "\n") {
			line = strings.TrimSpace(line)
			if !strings.HasPrefix(line, "image: ") {
				continue
			}
			ref := strings.TrimPrefix(line, "image: ")
			if strings.Contains(ref, "{{") || strings.Contains(ref, "$") {
				continue
			}
			if !kinds.ParseReference(ref).Pinned() {
				t.Errorf("%s renders %q, which does not name one build", f.Path, ref)
			}
		}
	}
}

// Not every application is configured by environment variables, and a design
// that can only render an .env cannot configure two of the five kinds here.
// WriteFreely reads an INI file and Synapse reads homeserver.yaml, and both
// carry credentials, so both must be rendered and both must be 0600.
func TestTemplateSetsRenderEachKindsOwnFiles(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	cases := []struct {
		path    string
		mode    uint32
		carries string
	}{
		{"home-a/srv/blog/config.ini", 0o600, "type = postgres"},
		{"vm/srv/chat/homeserver.yaml", 0o600, "name: psycopg2"},
		{"home-a/srv/talk/.env", 0o600, "DATABASE_URL="},
		{"home-a/srv/talk/compose.yaml", 0o644, "name: paisans-talk"},
		// A template's path is its destination, nested directories included.
		{"vm/srv/chat/initdb.d/01-mas-database.sql", 0o644, "CREATE DATABASE"},
	}
	for _, tc := range cases {
		f, ok := files[tc.path]
		if !ok {
			t.Errorf("%s was not rendered", tc.path)
			continue
		}
		if f.Mode != tc.mode {
			t.Errorf("%s rendered %04o, want %04o", tc.path, f.Mode, tc.mode)
		}
		if !strings.Contains(f.Content, tc.carries) {
			t.Errorf("%s does not contain %q:\n%s", tc.path, tc.carries, f.Content)
		}
	}

	// The blog is pinned, so it talks to the postgres container beside it,
	// the same host every other pinned app in this deployment connects to its
	// own sidecar on. The property worth asserting is that the two agree,
	// not merely that a connection exists: a wrong host would still start the
	// container and only fail at the first query.
	configIni, ok := files["home-a/srv/blog/config.ini"]
	if !ok {
		t.Fatal("the blog's config.ini was not rendered")
	}
	if !strings.Contains(configIni.Content, "host = postgres") {
		t.Errorf("home-a/srv/blog/config.ini does not point at the postgres container beside it:\n%s", configIni.Content)
	}
	composeYaml, ok := files["home-a/srv/blog/compose.yaml"]
	if !ok {
		t.Fatal("the blog's compose.yaml was not rendered")
	}
	if !strings.Contains(composeYaml.Content, "postgres:") {
		t.Error("home-a/srv/blog/compose.yaml does not declare the postgres service config.ini connects to")
	}
}

// The fork reads these keys and validates them at load rather than at the
// first upload, so a wrong key name is a container that will not start.
// Checked against config/config.go and config/storage.go on the fork's
// develop branch.
func TestTheBlogReadsPostgresAndS3(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}
	conf, ok := files["home-a/srv/blog/config.ini"]
	if !ok {
		t.Fatal("the blog's config.ini was not rendered")
	}

	// The endpoint is a fact of the fixture (garageEndpointHost picks the
	// first Garage site by sorted name), not of this change, so it is read
	// from the committed golden tree rather than guessed, the same way
	// TestObjectStorageIsPublishedOnTheMediaHostname reads Mbin's.
	golden, err := os.ReadFile(filepath.Join("testdata", "golden", "home-a", "srv", "talk", ".env"))
	if err != nil {
		t.Fatalf("reading the golden talk .env: %v", err)
	}
	endpoint := ""
	for _, line := range strings.Split(string(golden), "\n") {
		if strings.HasPrefix(line, "S3_ENDPOINT=") {
			endpoint = strings.TrimPrefix(line, "S3_ENDPOINT=")
		}
	}
	if endpoint == "" {
		t.Fatal("the golden tree has no S3_ENDPOINT to compare against")
	}

	for _, want := range []string{
		"type = postgres",
		"type = s3",
		"s3_endpoint = " + endpoint,
		"s3_bucket = blog-uploads",
		"s3_access_key_id = ",
		"s3_secret_access_key = ",
		// Path style addressing, rendered rather than defaulted: Garage
		// cannot serve bucket.endpoint/key, and a fork release that flipped
		// its own default would otherwise break every image with nothing in
		// the configuration to explain it.
		"s3_virtual_host = false",
		// The [storage] block above is inert without this. uploads.enabled
		// defaults to false in the fork, and with it false POST
		// /api/me/images is not routed, the /uploads/ route is gated off,
		// and checkUploadsAtStartup never runs, so a wrong bucket or a
		// refused key is not reported at boot either.
		"[uploads]",
		"enabled = true",
		"max_size_mb = 10",
		// Two settings the fork's registry rejects at the zero an absent key
		// leaves behind, logging an ERROR on every boot until they are
		// rendered.
		"min_username_len = 3",
	} {
		if !strings.Contains(conf.Content, want) {
			t.Errorf("config.ini is missing %q:\n%s", want, conf.Content)
		}
	}
	if strings.Contains(conf.Content, "type = sqlite3") {
		t.Error("the fork keeps its data in Postgres, so the SQLite section should be gone")
	}
	// uploads.dir names a path on this node and only the local image store
	// reads it. Rendering it beside type = s3 would describe a directory
	// nothing consults.
	if strings.Contains(conf.Content, "dir = ") {
		t.Errorf("uploads.dir is not read with an S3 store, so it should not be rendered:\n%s", conf.Content)
	}
}

// A secret in a bind mounted file is not visible through `docker inspect` or
// /proc/<pid>/environ, which is the reason a file configured application is the
// better case rather than the awkward one. That only holds if the file is 0600.
func TestEverySecretBearingFileIs0600(t *testing.T) {
	needles := []string{"fixture-not-a-secret", "client-secret"}
	for _, f := range build(t).Files {
		carries := false
		for _, needle := range needles {
			if strings.Contains(f.Content, needle) {
				carries = true
			}
		}
		if carries && f.Mode != 0o600 {
			t.Errorf("%s carries a credential and is %04o, not 0600", f.Path, f.Mode)
		}
	}
}

// Routing is assembled from per kind snippets rather than written into one
// file that knows every kind. The gateway keeps what is cross cutting; each app
// brings its own block, wherever it runs.
func TestTheGatewayImportsEachAppsOwnSnippet(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	caddyfile, ok := files["vm/srv/infra/caddy/Caddyfile"]
	if !ok {
		t.Fatal("the gateway rendered no Caddyfile")
	}
	for _, app := range []string{"talk", "docs", "auth", "blog", "chat"} {
		snippet := "vm/srv/infra/caddy/snippets/" + app + ".caddy"
		if _, ok := files[snippet]; !ok {
			t.Errorf("%s was not rendered onto the gateway", snippet)
		}
		if !strings.Contains(caddyfile.Content, "import /etc/caddy/snippets/"+app+".caddy") {
			t.Errorf("the Caddyfile does not import %s's snippet:\n%s", app, caddyfile.Content)
		}
	}

	// The gateway holds no application specific routing of its own. A proxy
	// directive here would be the conditional file this design rejects,
	// growing with every application added.
	if strings.Contains(caddyfile.Content, "reverse_proxy") {
		t.Errorf("the gateway file routes an application itself:\n%s", caddyfile.Content)
	}

	// A snippet is rendered onto the gateway, never into the app's own
	// directory, because that is not where it is read.
	for path := range files {
		if strings.HasSuffix(path, "caddy.snippet") || strings.Contains(path, "/srv/talk/caddy") {
			t.Errorf("%s put an app's routing beside the app", path)
		}
	}

	// A snippet never hardcodes where its app runs: a pinned app gets one
	// upstream and a clustered one gets every apps site, both from inventory.
	pinned := files["vm/srv/infra/caddy/snippets/chat.caddy"].Content
	if !strings.Contains(pinned, "10.44.0.3:8008") {
		t.Errorf("a pinned app's snippet does not point at its site:\n%s", pinned)
	}
	clustered := files["vm/srv/infra/caddy/snippets/talk.caddy"].Content
	if !strings.Contains(clustered, "10.44.0.1:8080 10.44.0.2:8080") {
		t.Errorf("a clustered app's snippet does not point at both apps sites:\n%s", clustered)
	}
}

// Trusted proxies are the mesh subnet and never a host address, which is what
// lets the gateway role move later without breaking client address handling.
func TestTrustedProxiesAreTheMeshSubnet(t *testing.T) {
	// Not every kind takes a trusted proxy setting, and one of those that does
	// is not configured by environment at all, so the assertion is about every
	// rendered file that mentions one rather than about `.env` files.
	var saw int
	for _, f := range build(t).Files {
		if !strings.Contains(f.Content, "TRUSTED_PROXIES") {
			continue
		}
		saw++
		if !strings.Contains(f.Content, "TRUSTED_PROXIES=10.44.0.0/24") {
			t.Errorf("%s does not trust the mesh subnet:\n%s", f.Path, f.Content)
		}
		for _, address := range []string{"TRUSTED_PROXIES=10.44.0.1", "TRUSTED_PROXIES=10.44.0.2", "TRUSTED_PROXIES=10.44.0.3"} {
			if strings.Contains(f.Content, address) {
				t.Errorf("%s trusts a specific host", f.Path)
			}
		}
	}
	if saw == 0 {
		t.Fatal("no rendered file set a trusted proxy, so this proved nothing")
	}
}

// The mesh subnet is whatever the file declares, not a constant in the code.
// It reaches both the trusted proxy list and the WireGuard interface address.
func TestMeshSubnetComesFromTheConfiguration(t *testing.T) {
	cfg := fixture(t)
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	cfg.Mesh.Subnet = "10.77.0.0/16"
	for name, site := range cfg.Sites {
		site.Address = strings.Replace(site.Address, "10.44.0.", "10.77.0.", 1)
		cfg.Sites[name] = site
	}
	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatal(err)
	}
	var sawEnv, sawInterface bool
	for _, f := range plan.Files {
		if strings.Contains(f.Content, "TRUSTED_PROXIES") {
			sawEnv = true
			if !strings.Contains(f.Content, "TRUSTED_PROXIES=10.77.0.0/16") {
				t.Errorf("%s did not follow the declared mesh:\n%s", f.Path, f.Content)
			}
		}
		if strings.HasSuffix(f.Path, "wg0.conf") {
			sawInterface = true
			if !strings.Contains(f.Content, "/16\n") {
				t.Errorf("%s did not use the declared prefix length:\n%s", f.Path, f.Content)
			}
		}
	}
	if !sawEnv || !sawInterface {
		t.Fatal("the test did not reach the files it checks")
	}
}

// No named volumes anywhere: a stack under /srv relocates with one tar.
func TestNoNamedVolumes(t *testing.T) {
	for _, f := range build(t).Files {
		if !strings.HasSuffix(f.Path, "compose.yaml") {
			continue
		}
		inVolumes := false
		for _, line := range strings.Split(f.Content, "\n") {
			trimmed := strings.TrimSpace(line)
			if trimmed == "volumes:" {
				if !strings.HasPrefix(line, " ") {
					t.Errorf("%s declares a top level volumes block, which is what named volumes look like", f.Path)
				}
				inVolumes = true
				continue
			}
			if !strings.HasPrefix(trimmed, "- ") {
				inVolumes = false
				continue
			}
			if !inVolumes {
				continue
			}
			mount := strings.TrimPrefix(trimmed, "- ")
			if !strings.HasPrefix(mount, "/srv/") && !strings.HasPrefix(mount, "/dev/") {
				t.Errorf("%s mounts something that is not a bind mount under /srv: %s", f.Path, mount)
			}
		}
	}
}

// Compose resolves an env_file path against the directory holding compose.yaml
// and refuses to load the project when the file is not there, so a path that
// names nothing stops the whole stack rather than one setting. The gateway's
// caddy service shipped exactly that: `caddy.env` beside compose.yaml, while
// the file was rendered into caddy/. Checking the parsed paths against the
// rendered tree catches the next one without needing Docker in the test.
func TestEveryEnvFileIsRendered(t *testing.T) {
	files := map[string]bool{}
	plan := build(t)
	for _, f := range plan.Files {
		files[f.Path] = true
	}
	checked := 0
	for _, f := range plan.Files {
		if !strings.HasSuffix(f.Path, "/compose.yaml") {
			continue
		}
		var doc struct {
			Services map[string]struct {
				EnvFile yaml.Node `yaml:"env_file"`
			} `yaml:"services"`
		}
		if err := yaml.Unmarshal([]byte(f.Content), &doc); err != nil {
			t.Fatalf("%s does not parse: %v", f.Path, err)
		}
		dir := path.Dir(f.Path)
		for name, service := range doc.Services {
			var entries []string
			switch service.EnvFile.Kind {
			case 0:
				continue
			case yaml.ScalarNode:
				entries = []string{service.EnvFile.Value}
			case yaml.SequenceNode:
				for _, item := range service.EnvFile.Content {
					entries = append(entries, item.Value)
				}
			default:
				t.Errorf("%s: service %s has an env_file this test does not understand", f.Path, name)
				continue
			}
			for _, entry := range entries {
				resolved := path.Join(dir, entry)
				if !files[resolved] {
					t.Errorf("%s: service %s reads env_file %s, which resolves to %s and is not rendered", f.Path, name, entry, resolved)
				}
				checked++
			}
		}
	}
	if checked == 0 {
		t.Fatal("no env_file was found in any rendered compose file, so this test checked nothing")
	}
}

// DNS-01 for every hostname, so a gateway can hold valid certificates before
// any DNS record points at it. That is what makes moving the gateway an
// overlap rather than a cutover.
func TestGatewayUsesDNSChallenge(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}
	caddyfile, ok := files["vm/srv/infra/caddy/Caddyfile"]
	if !ok {
		t.Fatal("no Caddyfile was rendered for the gateway")
	}
	if !strings.Contains(caddyfile, "acme_dns desec") {
		t.Errorf("the gateway does not use DNS-01:\n%s", caddyfile)
	}
	if _, ok := files["vm/srv/infra/caddy/caddy.env"]; !ok {
		t.Error("the DNS provider token was not rendered for the gateway")
	}
	for path := range files {
		if strings.HasSuffix(path, "caddy.env") && !strings.HasPrefix(path, "vm/") {
			t.Errorf("%s holds the zone token on a site that is not the gateway", path)
		}
	}
}

// Every app has its own database credential. A shared one reads every other
// app's data, since one cluster holds them all.
func TestEachAppHasItsOwnDatabasePassword(t *testing.T) {
	seen := map[string]string{}
	for _, f := range build(t).Files {
		if !strings.HasSuffix(f.Path, "/.env") {
			continue
		}
		parts := strings.Split(f.Path, "/")
		app := parts[len(parts)-2]
		for _, line := range strings.Split(f.Content, "\n") {
			if !strings.Contains(line, "fixture-not-a-secret-") || !strings.Contains(line, "-db") {
				continue
			}
			value := line[strings.Index(line, "fixture-not-a-secret-"):]
			if previous, ok := seen[value]; ok && previous != app {
				t.Errorf("%s and %s share a database credential", previous, app)
			}
			seen[value] = app
		}
	}
	if len(seen) < 4 {
		t.Fatalf("expected a distinct credential per app, found %d", len(seen))
	}
	if strings.Contains(strings.Join(keys(seen), " "), "admin") {
		t.Error("an app was given the cluster admin password")
	}
}

func keys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

// The manifest is what lets a later apply tell an untouched artifact from one
// somebody edited on the host.
func TestManifestCoversEveryFile(t *testing.T) {
	dir := t.TempDir()
	plan := build(t)
	if err := render.Write(plan, dir); err != nil {
		t.Fatal(err)
	}
	for _, site := range []string{"home-a", "home-b", "vm"} {
		data, err := os.ReadFile(filepath.Join(dir, site, render.ManifestName))
		if err != nil {
			t.Fatalf("reading the manifest for %s: %v", site, err)
		}
		for _, f := range plan.Files {
			prefix := site + "/"
			if !strings.HasPrefix(f.Path, prefix) {
				continue
			}
			if !strings.Contains(string(data), strings.TrimPrefix(f.Path, prefix)) {
				t.Errorf("%s is missing from %s's manifest", f.Path, site)
			}
		}
	}
}

func compareTrees(t *testing.T, want, got string) {
	t.Helper()
	wantFiles := walk(t, want)
	gotFiles := walk(t, got)

	for path, content := range wantFiles {
		other, ok := gotFiles[path]
		if !ok {
			t.Errorf("%s is missing from the rendered tree", path)
			continue
		}
		if content != other {
			t.Errorf("%s differs.\nwant:\n%s\ngot:\n%s", path, content, other)
		}
	}
	for path := range gotFiles {
		if _, ok := wantFiles[path]; !ok {
			t.Errorf("%s was rendered but is not in the golden tree", path)
		}
	}
}

func walk(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(rel)] = string(data)
		return nil
	})
	if err != nil {
		t.Fatalf("walking %s: %v", root, err)
	}
	return out
}

// Every template a kind ships has to be committed, and the templates that
// render an .env are the ones at risk: the repository ignores `.env.*` so that
// no real credential is ever committed, and the four files named
// `.env.secret.tmpl` match that rule by accident.
//
// The failure mode is why this test exists rather than a comment. The files
// stay on the machine that wrote them, where every test passes, and a fresh
// checkout renders a stack with no environment at all. Reading the embedded
// filesystem catches it, because embed sees exactly what git checked out.
func TestEveryKindShipsACommittedTemplateSet(t *testing.T) {
	for _, kind := range []config.Kind{
		config.KindMbin, config.KindOutline, config.KindPocketID,
		config.KindSynapse, config.KindWriteFreely,
	} {
		files, err := render.TemplateSet(kind)
		if err != nil {
			t.Errorf("%s: %v", kind, err)
			continue
		}
		var compose, config bool
		for _, name := range files {
			switch {
			case strings.HasSuffix(name, "compose.yaml.tmpl"):
				compose = true
			case strings.HasSuffix(name, ".env.secret.tmpl"),
				strings.HasSuffix(name, "config.ini.secret.tmpl"),
				strings.HasSuffix(name, "homeserver.yaml.secret.tmpl"):
				config = true
			}
		}
		if !compose {
			t.Errorf("%s ships no compose template", kind)
		}
		if !config {
			t.Errorf("%s ships no configuration template, so the stack would start unconfigured. Check that it is committed: the repository ignores .env.*", kind)
		}
	}
}

// The provider reaches the gateway's configuration, and the credential is named
// for what it is rather than for whoever issues it.
func TestTheDeclaredProviderIsRendered(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}

	caddyfile := files["vm/srv/infra/caddy/Caddyfile"]
	if !strings.Contains(caddyfile, "acme_dns desec {") {
		t.Errorf("the gateway does not use the declared provider:\n%s", caddyfile)
	}
	if !strings.Contains(caddyfile, "token {env.ACME_DNS_TOKEN}") {
		t.Errorf("the gateway does not pass the credential to desec's block form:\n%s", caddyfile)
	}
	if strings.Contains(caddyfile, "cloudflare") {
		t.Errorf("a provider nobody declared appears in the gateway config:\n%s", caddyfile)
	}

	env := files["vm/srv/infra/caddy/caddy.env"]
	if !strings.Contains(env, "ACME_DNS_TOKEN=") {
		t.Errorf("the credential is not rendered under a provider neutral name:\n%s", env)
	}
	if strings.Contains(env, "CLOUDFLARE") {
		t.Errorf("a provider's name survives in the environment:\n%s", env)
	}
}

// The image a gateway runs is the one that carries the declared provider's
// module, pinned by digest, and never upstream's own image.
func TestTheGatewayRunsAnImageWithTheModule(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}
	infra := files["vm/srv/infra/compose.yaml"]
	want, ok := acme.Image("desec")
	if !ok {
		t.Fatal("desec has no published image")
	}
	if !strings.Contains(infra, "image: "+want) {
		t.Errorf("the gateway does not run the image carrying its provider:\n%s", infra)
	}
	if strings.Contains(infra, "image: caddy:") {
		t.Errorf("the gateway runs upstream's image, which carries no DNS module:\n%s", infra)
	}
}

// The escape hatch has to actually work: a declared image is what keeps a
// provider the toolkit publishes nothing for from being lock-in, and it is
// worth nothing unless it reaches the gateway's compose file in place of the
// published one.
func TestADeclaredImageReachesTheGateway(t *testing.T) {
	cfg := fixture(t)
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	// A provider the toolkit publishes no image for, with the adopter's own
	// image carrying its module. This is the configuration README calls the
	// anti lock-in path.
	cfg.ACME.Provider = "route53"
	cfg.ACME.Image = "ghcr.io/example-org/caddy-route53:2.11.4"

	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatalf("a declared image and an unpublished provider failed to render: %v", err)
	}
	files := map[string]string{}
	for _, f := range plan.Files {
		files[f.Path] = f.Content
	}

	infra := files["vm/srv/infra/compose.yaml"]
	if !strings.Contains(infra, "image: "+cfg.ACME.Image) {
		t.Errorf("the gateway does not run the declared image:\n%s", infra)
	}
	published, _ := acme.Image("desec")
	if strings.Contains(infra, published) {
		t.Errorf("the published image survived a declared one:\n%s", infra)
	}
	if caddyfile := files["vm/srv/infra/caddy/Caddyfile"]; !strings.Contains(caddyfile, "acme_dns route53") {
		t.Errorf("an unpublished provider does not reach the directive:\n%s", caddyfile)
	}
}

// A deployment with no gateway site is legitimate: internal/config requires
// acme.provider only when a site holds the gateway role. The renderer must not
// demand a Caddy image for a site that will never run Caddy, or a config that
// validation accepts fails to render anyway, over an image nothing needs.
func TestNoGatewayNeedsNoACMEProvider(t *testing.T) {
	cfg := fixture(t)
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	cfg.ACME = config.ACME{}
	vm := cfg.Sites["vm"]
	vm.Roles = []config.Role{config.RoleWitness}
	cfg.Sites["vm"] = vm

	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatalf("a deployment with no gateway site failed to render: %v", err)
	}
	for _, f := range plan.Files {
		if strings.HasSuffix(f.Path, "caddy/Caddyfile") {
			t.Errorf("%s was rendered although no site holds the gateway role", f.Path)
		}
	}
}

// Element is a static web client: no database, no secrets of its own, and a
// runtime configuration naming the homeserver it talks to.
func TestElementRendersAClientConfig(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	compose, ok := files["home-b/srv/web/compose.yaml"]
	if !ok {
		t.Fatal("the element app was not rendered")
	}
	if strings.Contains(compose.Content, "postgres") {
		t.Error("element was given a database, and it has no state at all")
	}

	config, ok := files["home-b/srv/web/config.json"]
	if !ok {
		t.Fatal("element rendered no runtime configuration")
	}
	if !strings.Contains(config.Content, `"base_url": "https://chat.example.org"`) {
		t.Errorf("element's config does not name its homeserver:\n%s", config.Content)
	}
	// base_url is where the API is; server_name is the part after the colon in
	// a user identifier. They are different names whenever delegation is in
	// use, and a client that offers the wrong one offers accounts that do not
	// exist. It must be the same value the homeserver was given.
	homeserver := files["vm/srv/chat/homeserver.yaml"].Content
	if !strings.Contains(homeserver, `server_name: "example.org"`) {
		t.Fatalf("the fixture homeserver's server_name is not what this test assumes:\n%s", homeserver)
	}
	if !strings.Contains(config.Content, `"server_name": "example.org"`) {
		t.Errorf("element and the homeserver disagree about server_name:\n%s", config.Content)
	}
	if config.Mode != 0o644 {
		t.Errorf("element's config is %04o; it carries no secret and wants 0644", config.Mode)
	}
}

// One app can answer on several hostnames, and each gets its own routing. The
// case that forces it: a Matrix homeserver serves its API on one name and its
// .well-known delegation on the apex, and those are not the same routing.
func TestAnAppCanHoldSeveralHostnames(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	caddyfile, ok := files["vm/srv/infra/caddy/Caddyfile"]
	if !ok {
		t.Fatal("no gateway configuration was rendered")
	}
	for _, hostname := range []string{"chat.example.org", "example.org"} {
		if !strings.Contains(caddyfile.Content, "\n"+hostname+" {") {
			t.Errorf("the gateway has no host block for %s:\n%s", hostname, caddyfile.Content)
		}
	}

	// Each hostname imports its own snippet, because the apex serves only the
	// delegation documents while the primary serves the whole API.
	if _, ok := files["vm/srv/infra/caddy/snippets/chat.caddy"]; !ok {
		t.Error("the primary hostname has no snippet")
	}
	if _, ok := files["vm/srv/infra/caddy/snippets/chat-wellknown.caddy"]; !ok {
		t.Error("the extra hostname has no snippet of its own")
	}
}

// The gate is two instances, not one: a visitor who has authenticated is not
// yet a member, and the two are allowed to reach different applications.
func TestTheAuthGateRendersBothInstances(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	compose, ok := files["home-a/srv/gate/compose.yaml"]
	if !ok {
		t.Fatal("the gate was not rendered")
	}
	for _, service := range []string{"provisional:", "members:"} {
		if !strings.Contains(compose.Content, service) {
			t.Errorf("the gate is missing its %s instance:\n%s", service, compose.Content)
		}
	}

	env, ok := files["home-a/srv/gate/.env"]
	if !ok {
		t.Fatal("the gate rendered no environment")
	}
	if env.Mode != 0o600 {
		t.Errorf("the gate's environment is %04o and it carries a client secret", env.Mode)
	}
	if !strings.Contains(env.Content, "OIDC_ISSUER_URL=https://id.example.org") {
		t.Errorf("the gate does not point at the identity provider:\n%s", env.Content)
	}
}

// gate_provisional and gate_members are named snippets, not a hostname's
// routing: nothing imports this file by path, and they must be defined before
// anything can import them by name.
func TestTheAuthGateShipsNamedSnippets(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	gates, ok := files["vm/srv/infra/caddy/snippets/gate-gates.caddy"]
	if !ok {
		t.Fatal("the gate's named snippets were not rendered onto the gateway")
	}
	for _, name := range []string{"(gate_provisional)", "(gate_members)"} {
		if !strings.Contains(gates.Content, name) {
			t.Errorf("the gate's snippet file does not define %s:\n%s", name, gates.Content)
		}
	}

	caddyfile, ok := files["vm/srv/infra/caddy/Caddyfile"]
	if !ok {
		t.Fatal("no gateway configuration was rendered")
	}
	if !strings.Contains(caddyfile.Content, "import /etc/caddy/snippets/gate-gates.caddy") {
		t.Errorf("the Caddyfile does not import the gate's named snippets:\n%s", caddyfile.Content)
	}
}

// Which gate an app sits behind is policy, and it is declared rather than
// implied by which snippet somebody remembered to import.
func TestTheGateIsDeclaredPerApp(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}
	caddyfile := files["vm/srv/infra/caddy/Caddyfile"].Content

	// talk sits behind the members gate in the fixture.
	if !strings.Contains(caddyfile, "import gate_members") {
		t.Errorf("a gated app's host block does not import its gate:\n%s", caddyfile)
	}

	// A Matrix client is not a browser and will not follow a redirect to a
	// passkey prompt, so chat and its apex must never be gated.
	for _, hostname := range []string{"chat.example.org", "example.org"} {
		block := hostBlock(t, caddyfile, hostname)
		if strings.Contains(block, "import gate_") {
			t.Errorf("%s is gated, which breaks every Matrix client:\n%s", hostname, block)
		}
	}
}

// Synapse is a resource server: MAS owns authentication, and Synapse must not
// carry a second way in. The single check that proves the split is that no
// oidc_providers block is rendered and the delegation to MAS is.
//
// The brief for this task asked for `msc3861` here, which is the experimental
// form. Synapse v1.160.0, the version this kind pins, documents the stable
// `matrix_authentication_service` block instead and its configuration manual
// no longer mentions msc3861 at all: checked against
// docs/usage/configuration/config_documentation.md at tag v1.160.0 on
// 2026-09-15. Asserting the experimental key would pin the toolkit to a shape
// the pinned image has moved past, so the stable one is asserted and the
// deviation is recorded in docs/decisions.md.
func TestSynapseDelegatesAuthenticationToMAS(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	homeserver := files["vm/srv/chat/homeserver.yaml"].Content
	if strings.Contains(homeserver, "oidc_providers") {
		t.Error("homeserver.yaml still configures its own OIDC, which is a second way in")
	}
	if strings.Contains(homeserver, "registration_shared_secret") {
		t.Error("registration_shared_secret is present, which bypasses MAS and the group restriction")
	}
	if !strings.Contains(homeserver, "matrix_authentication_service:") {
		t.Errorf("homeserver.yaml does not delegate to MAS:\n%s", homeserver)
	}

	mas, ok := files["vm/srv/chat/mas.yaml"]
	if !ok {
		t.Fatal("no MAS configuration was rendered")
	}
	if mas.Mode != 0o600 {
		t.Error("the MAS configuration carries secrets and must be 0600")
	}

	compose := files["vm/srv/chat/compose.yaml"].Content
	if !strings.Contains(compose, "mas:") {
		t.Error("the stack renders no MAS service")
	}
}

// Both sides of the shared secret have to be the same string, or Synapse and
// MAS each start cleanly and refuse every request between them.
func TestSynapseAndMASShareOneSecret(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}
	secret := "fixture-not-a-secret-chat-mas-matrix"
	for _, path := range []string{"vm/srv/chat/homeserver.yaml", "vm/srv/chat/mas.yaml"} {
		if !strings.Contains(files[path].Content, secret) {
			t.Errorf("%s does not carry the shared secret both sides need:\n%s", path, files[path].Content)
		}
	}
}

// MAS answers the three compatibility login paths, and if the /_matrix/* catch
// all captured them instead, every login would reach Synapse, which no longer
// knows how to answer one.
//
// What decides between them is matcher length, not the order they are written
// in: Caddy sorts routes of one directive longest matcher first, trailing
// wildcard trimmed (caddyconfig/httpcaddyfile/directives.go, sortRoutes, read
// at v2.11.4, the version this toolkit pins). An earlier version of this test
// asserted byte offsets in the rendered file and was named for order, which
// would not have caught the failure it named: the same snippet already writes
// /.well-known/matrix/* after both catch alls, and it wins anyway.
//
// This test asserts the property that governs, and only that. It reads
// rendered text, so it cannot observe what Caddy does with the sorted routes;
// proving that needs a running Caddy, which this suite does not have. The name
// says what is checked so that nobody reads a guarantee into it that is not
// here.
func TestTheLoginSplitOutranksTheCatchAllByMatcherLength(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}
	snippet, ok := files["vm/srv/infra/caddy/snippets/chat.caddy"]
	if !ok {
		t.Fatal("the homeserver has no snippet")
	}

	// matcherLength is what Caddy compares. It sorts routes of one directive
	// by path matcher length with a trailing wildcard trimmed, longest first.
	matcherLength := func(path string) int { return len(strings.TrimSuffix(path, "*")) }

	const catchAll = "/_matrix/*"
	if !strings.Contains(snippet.Content, "handle "+catchAll+" {") {
		t.Fatalf("the snippet has no %s catch all:\n%s", catchAll, snippet.Content)
	}
	for _, path := range []string{
		"/_matrix/client/*/login",
		"/_matrix/client/*/logout",
		"/_matrix/client/*/refresh",
	} {
		if !strings.Contains(snippet.Content, "handle "+path+" {") {
			t.Errorf("the snippet does not split %s off to MAS:\n%s", path, snippet.Content)
			continue
		}
		if matcherLength(path) <= matcherLength(catchAll) {
			t.Errorf("%s does not outrank %s on matcher length, so Caddy may sort the catch all ahead of it and Synapse answers the login",
				path, catchAll)
		}
	}
}

// The apex serves the delegation documents and nothing else. Routing it like
// the primary would publish the whole homeserver API there.
func TestTheApexServesOnlyDelegation(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}
	snippet, ok := files["vm/srv/infra/caddy/snippets/chat-wellknown.caddy"]
	if !ok {
		t.Fatal("the apex has no snippet")
	}
	if !strings.Contains(snippet.Content, "/.well-known/matrix/") {
		t.Errorf("the apex snippet does not serve the delegation documents:\n%s", snippet.Content)
	}
	if strings.Contains(snippet.Content, "/_matrix/") {
		t.Errorf("the apex snippet exposes the homeserver API:\n%s", snippet.Content)
	}
	// The name in every user identifier is the name the delegation is served
	// on, so that is what server_name has to be. If they disagree, the two
	// documents below point nowhere and federation resolves to the wrong host.
	homeserver := files["vm/srv/chat/homeserver.yaml"].Content
	if !strings.Contains(homeserver, `server_name: "example.org"`) {
		t.Errorf("server_name is not the name the delegation is served on:\n%s", homeserver)
	}
	for _, document := range []string{"/.well-known/matrix/server", "/.well-known/matrix/client"} {
		if !strings.Contains(snippet.Content, "handle "+document+" {") {
			t.Errorf("the apex does not answer %s:\n%s", document, snippet.Content)
		}
	}
}

// A homeserver that declares no delegation hostname answers the delegation
// documents itself, and the gateway has to send them to it.
//
// The fixture always declares one, so the golden tree never exercises this
// branch: a snippet that quietly routed /.well-known/matrix/* to MAS instead
// would render, review cleanly and leave a federating peer with a 404 that
// sends it to <server_name>:8448, where nothing listens.
func TestAHomeserverWithNoDelegationServesItsOwnWellKnown(t *testing.T) {
	cfg := fixture(t)
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	chat := cfg.Apps["chat"]
	chat.Hostnames = nil
	cfg.Apps["chat"] = chat

	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatalf("a homeserver with no delegation hostname failed to render: %v", err)
	}
	files := map[string]render.File{}
	for _, f := range plan.Files {
		files[f.Path] = f
	}

	if _, ok := files["vm/srv/infra/caddy/snippets/chat-wellknown.caddy"]; ok {
		t.Error("a snippet was rendered for a hostname role nobody declared")
	}

	homeserver := files["vm/srv/chat/homeserver.yaml"].Content
	if !strings.Contains(homeserver, "serve_server_wellknown: true") {
		t.Errorf("the homeserver was not told to serve its own delegation:\n%s", homeserver)
	}
	if !strings.Contains(homeserver, `server_name: "chat.example.org"`) {
		t.Errorf("server_name is not the only hostname this app has:\n%s", homeserver)
	}

	snippet := files["vm/srv/infra/caddy/snippets/chat.caddy"].Content
	at := strings.Index(snippet, "handle /.well-known/matrix/* {")
	if at < 0 {
		t.Fatalf("the gateway does not route the delegation documents anywhere:\n%s", snippet)
	}
	// Anywhere is not good enough: MAS does not serve them, and the bare
	// handle at the end of the snippet is MAS's.
	homeserverUpstream := "10.44.0.3:8008"
	rest := snippet[at:]
	end := strings.Index(rest, "\n}")
	if end < 0 {
		t.Fatalf("unterminated handle:\n%s", rest)
	}
	if !strings.Contains(rest[:end], homeserverUpstream) {
		t.Errorf("the delegation documents do not reach the homeserver:\n%s", rest[:end])
	}
}

// hostBlock returns the text of one host block, so a test can assert about one
// hostname rather than about the whole file.
func hostBlock(t *testing.T, caddyfile, hostname string) string {
	t.Helper()
	start := strings.Index(caddyfile, "\n"+hostname+" {")
	if start < 0 {
		t.Fatalf("no host block for %s", hostname)
	}
	end := strings.Index(caddyfile[start+1:], "\n}")
	if end < 0 {
		t.Fatalf("unterminated host block for %s", hostname)
	}
	return caddyfile[start : start+end]
}

// The endpoint an app writes through and the URL it publishes are different
// strings for a reason, though what crosses the gateway differs by app. Mbin
// writes to its endpoint itself, server side, over the mesh, so its uploads
// never cross the gateway; only the URL it publishes does. Outline's server
// never writes bytes to S3 at all: it issues a presigned POST the browser
// submits directly against the media hostname, so Outline's uploads cross the
// gateway too. Either way the published URL must resolve for a browser and
// for a federating server that will never join this mesh.
func TestObjectStorageIsPublishedOnTheMediaHostname(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}

	// The endpoint is a fact of the fixture (garageEndpointHost picks the
	// first Garage site by sorted name), not of this change, so it is read
	// from the committed golden tree rather than guessed. This proves the
	// endpoint an app writes through is unchanged, without this test owning
	// that address.
	golden, err := os.ReadFile(filepath.Join("testdata", "golden", "home-a", "srv", "talk", ".env"))
	if err != nil {
		t.Fatalf("reading the golden talk .env: %v", err)
	}
	endpointLine := ""
	for _, line := range strings.Split(string(golden), "\n") {
		if strings.HasPrefix(line, "S3_ENDPOINT=") {
			endpointLine = line
		}
	}
	if endpointLine == "" {
		t.Fatal("the golden tree has no S3_ENDPOINT to compare against")
	}

	env := files["home-a/srv/talk/.env"]
	if !strings.Contains(env, "KBIN_STORAGE_URL=https://media.example.org/talk-uploads") {
		t.Errorf("Mbin builds every media URL and every thumbnail root from KBIN_STORAGE_URL, got:\n%s", env)
	}
	if !strings.Contains(env, endpointLine) {
		t.Errorf("Mbin writes to Garage itself, server side, over the mesh, so its endpoint must still be the internal one, want %q in:\n%s", endpointLine, env)
	}

	outline := files["home-a/srv/docs/.env"]
	if !strings.Contains(outline, "AWS_S3_UPLOAD_BUCKET_URL=https://media.example.org") {
		t.Errorf("Outline publishes attachment URLs from its bucket URL, got:\n%s", outline)
	}

	caddyfile := files["vm/srv/infra/caddy/Caddyfile"]
	block := hostBlock(t, caddyfile, "media.example.org")
	if strings.Contains(block, "import gate_") {
		t.Error("the media hostname must never be gated: a federating server fetching an image is a machine")
	}

	snippet := files["vm/srv/infra/caddy/snippets/media.caddy"]
	if !strings.Contains(snippet, "3900") {
		t.Errorf("the media snippet should reach Garage on 3900, got:\n%s", snippet)
	}
	// Only a public bucket's own route rewrites Host, to reach the web
	// endpoint's vhost. The fallback, which is what Outline's presigned
	// reads take, must forward Host unchanged or its signatures stop
	// verifying. TestOnlyAPublicBucketIsRewrittenToTheWebEndpoint covers the
	// bucket route itself; this asserts the fallback never rewrites.
	//
	// Scoped to the fallback block rather than matched against a longer
	// string: any `header_up Host` at all in that region is the bug, whatever
	// value it carries.
	if fallback := fallbackHandle(t, snippet); strings.Contains(fallback, "header_up Host") {
		t.Errorf("the fallback must forward Host unchanged or Outline's presigned URLs stop verifying, got:\n%s", fallback)
	}
}

// Garage's S3 API has no anonymous mode at all, so the only way a browser can
// fetch an object is the s3_web endpoint. Its root_domain is a suffix nothing
// resolves: the gateway is the only thing that ever sends a Host matching it,
// and it never leaves the gateway, so there is no DNS record and no
// certificate for an adopter to set up.
func TestGarageServesAWebEndpointOnAnInternalSuffix(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}
	conf := files["home-a/srv/infra/garage/garage.toml"]
	if !strings.Contains(conf, "[s3_web]") {
		t.Errorf("no s3_web section, so nothing can read an object anonymously:\n%s", conf)
	}
	if !strings.Contains(conf, `root_domain = ".web.garage.internal"`) {
		t.Errorf("the web root domain should be the internal suffix, got:\n%s", conf)
	}
	if !strings.Contains(conf, ":3902") {
		t.Error("s3_web should bind 3902")
	}
	if strings.Contains(conf, "index =") {
		t.Error("no index document: a prefix with no object must 404 rather than return something else")
	}
}

// A public bucket's objects reach the web endpoint, which needs a vhost style
// Host. Everything else stays on the S3 API with Host untouched, because that
// is what makes Outline's presigned URLs verify.
//
// Caddy sorts same directive routes by path matcher length, longest first, so
// this asserts matcher length rather than the order the lines happen to be
// written in. The file order is not what decides it.
func TestOnlyAPublicBucketIsRewrittenToTheWebEndpoint(t *testing.T) {
	tree := build(t)
	files := map[string]string{}
	for _, f := range tree.Files {
		files[f.Path] = f.Content
	}
	snippet := files["vm/srv/infra/caddy/snippets/media.caddy"]

	// talk-uploads is Mbin's bucket in this fixture (app "talk", no
	// s3_bucket override, so the default is the app name plus "-uploads").
	if !strings.Contains(snippet, "handle /talk-uploads/*") {
		t.Errorf("mbin's bucket should have its own route:\n%s", snippet)
	}
	if !strings.Contains(snippet, "uri strip_prefix /talk-uploads") {
		t.Error("the bucket prefix must be stripped: the web endpoint takes the key as the path")
	}
	if !strings.Contains(snippet, "header_up Host talk-uploads.web.garage.internal") {
		t.Error("the web endpoint resolves the bucket from Host, so Host must be rewritten")
	}
	if !strings.Contains(snippet, ":3902") {
		t.Error("a public bucket's reads go to the web endpoint")
	}

	// Outline's bucket (docs-uploads, declared in the fixture) must not
	// appear at all. Its attachments are private and its reads are
	// presigned, so they belong on the S3 API with the fallback.
	if strings.Contains(snippet, "docs-uploads") {
		t.Errorf("outline's bucket must not be routed to the anonymous endpoint:\n%s", snippet)
	}

	// The blog's bucket (blog-uploads, the default for app "blog", no
	// s3_bucket override in the fixture) must not appear either, and for a
	// different reason than Outline's: the wisp fork streams its images
	// through its own /uploads/ route and never addresses the object store
	// from a browser at all, so there is no anonymous read to route here.
	if strings.Contains(snippet, "blog-uploads") {
		t.Errorf("the blog's bucket must not be routed to the anonymous endpoint:\n%s", snippet)
	}

	// The fallback keeps Host, which is the whole reason presigned URLs verify.
	if !strings.Contains(snippet, ":3900") {
		t.Error("the fallback should reach the S3 API")
	}
	if fallback := fallbackHandle(t, snippet); strings.Contains(fallback, "header_up Host") {
		t.Errorf("the fallback must not rewrite Host, got:\n%s", fallback)
	}

	// Matcher length, not file order, is what Caddy sorts on. Prove the
	// bucket route carries a path matcher and the fallback carries none,
	// which is the property that makes Caddy put the bucket route first.
	if !strings.Contains(snippet, "handle /talk-uploads/* {") {
		t.Errorf("the bucket route should carry a path matcher:\n%s", snippet)
	}
	if !strings.Contains(snippet, "handle {\n\treverse_proxy") {
		t.Errorf("the fallback route should carry no path matcher:\n%s", snippet)
	}
}

// fallbackHandle returns the text of the media snippet's fallback `handle`
// block: the one with no path matcher, which is what everything that is not a
// public bucket takes.
//
// A test that wants to say "the fallback does not rewrite Host" has to look at
// the fallback and nothing else, because the public bucket routes rewrite Host
// legitimately and a search over the whole snippet would always match. Scoping
// is what makes the assertion able to fail: an earlier version of it searched
// the whole file for a longer string the template cannot produce, which made it
// unfalsifiable and so no protection at all.
func fallbackHandle(t *testing.T, snippet string) string {
	t.Helper()
	open := strings.Index(snippet, "\nhandle {\n")
	if open < 0 {
		t.Fatalf("the media snippet has no fallback handle block:\n%s", snippet)
	}
	// Brace counting from the block's own opening brace, so a nested block
	// (the reverse_proxy body, when it has one) does not end the region early.
	start := open + len("\nhandle ")
	depth := 0
	for i := start; i < len(snippet); i++ {
		switch snippet[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return snippet[start : i+1]
			}
		}
	}
	t.Fatalf("unterminated fallback handle block:\n%s", snippet[start:])
	return ""
}

// requiredComposeVar matches a `${VAR:?message}` reference, which is Compose's
// way of saying the variable has no default. Compose aborts the entire `up`
// when one is unset, so every such reference is a hard dependency on something
// else in the same stack directory.
var requiredComposeVar = regexp.MustCompile(`\$\{([A-Za-z_][A-Za-z0-9_]*):\?`)

// A rendered compose file and the rendered `.env` beside it are two halves of
// one thing, and only compose knows that. It reads `.env` from the project
// directory for ${VAR} substitution whether or not a service declares
// env_file, so a `${VAR:?...}` reference with no matching assignment is a
// stack that cannot start at all: `docker compose up` aborts before creating
// anything, naming the variable.
//
// This repository has lost a template to .gitignore twice, and the shape of
// that loss is exactly this. `.env.secret.tmpl` matches the `.env.*` ignore
// rule, so deleting one, or failing to commit it, is invisible: every other
// test still passes, the golden tree regenerates happily without it, and
// TestEveryKindShipsACommittedTemplateSet is satisfied by any one of several
// configuration file suffixes, so a kind that ships a `config.ini.secret.tmpl`
// passes with its `.env.secret.tmpl` gone.
//
// Checking the references rather than a per kind file list is what makes this
// catch the class: a new kind, a new variable or a renamed template is covered
// without anybody remembering to extend a list.
func TestEveryRequiredComposeVariableIsSetInTheStacksEnv(t *testing.T) {
	files := map[string]string{}
	var paths []string
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
		paths = append(paths, f.Path)
	}
	sort.Strings(paths)

	checked := 0
	for _, path := range paths {
		if filepath.Base(path) != "compose.yaml" {
			continue
		}
		refs := requiredComposeVar.FindAllStringSubmatch(files[path], -1)
		if len(refs) == 0 {
			continue
		}
		envPath := filepath.ToSlash(filepath.Join(filepath.Dir(path), ".env"))
		env, ok := files[envPath]
		if !ok {
			t.Errorf("%s requires %s but no %s is rendered, so `docker compose up` aborts and the stack never starts. A missing .env.secret.tmpl looks exactly like this: the repository ignores .env.*, so check that the template is committed.",
				path, refNames(refs), envPath)
			continue
		}
		for _, ref := range refs {
			name := ref[1]
			if !assignsEnvVar(env, name) {
				t.Errorf("%s requires %s, which %s does not set. `docker compose up` aborts naming that variable, before creating anything.", path, name, envPath)
			}
			checked++
		}
	}

	// A test that silently checked nothing would be the same failure as the
	// one it is here to catch. The fixture renders a pinned blog and a pinned
	// Synapse, so there is at least one reference to find.
	if checked == 0 {
		t.Fatal("no `${VAR:?...}` reference was found in any rendered compose file, so this test verified nothing")
	}
}

// refNames lists the variable names in a match set, for one readable message.
func refNames(refs [][]string) string {
	var names []string
	for _, ref := range refs {
		names = append(names, ref[1])
	}
	return strings.Join(names, ", ")
}

// assignsEnvVar reports whether a rendered `.env` assigns name. Compose takes
// the whole line, so an assignment is a line beginning with the name and an
// equals sign; a commented line is not one, and the leading "#" makes that
// fall out rather than needing a check.
func assignsEnvVar(env, name string) bool {
	for _, line := range strings.Split(env, "\n") {
		if strings.HasPrefix(line, name+"=") {
			return true
		}
	}
	return false
}

// fixtureSecrets loads the secrets every test in this file renders against.
func fixtureSecrets(t *testing.T) *config.Secrets {
	t.Helper()
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatalf("loading the fixture secrets: %v", err)
	}
	return secrets
}

// planFiles indexes a plan's files by path.
func planFiles(plan *render.Plan) map[string]string {
	out := map[string]string{}
	for _, f := range plan.Files {
		out[f.Path] = f.Content
	}
	return out
}

// withConfig returns the fixture with one app's passthrough map replaced.
func withConfig(t *testing.T, app string, keys map[string]any) *config.Config {
	t.Helper()
	cfg := fixture(t)
	a, ok := cfg.Apps[app]
	if !ok {
		t.Fatalf("the fixture declares no app %q", app)
	}
	a.Config = keys
	cfg.Apps[app] = a
	return cfg
}

// A passthrough key reaches the file its kind actually reads, in that file's
// syntax. One key per format, so the rendered output for each is visible in
// the tree an operator receives.
func TestAPassthroughKeyReachesTheRenderedFile(t *testing.T) {
	files := planFiles(build(t))

	env := files["home-a/srv/talk/.env"]
	if !strings.Contains(env, "\nKBIN_META_TITLE=A place to talk\n") {
		t.Errorf("mbin reads an environment:\n%s", env)
	}

	ini := files["home-a/srv/blog/config.ini"]
	app := strings.Index(ini, "\n[app]\n")
	if app < 0 {
		t.Fatalf("the blog's config.ini has no [app] section:\n%s", ini)
	}
	appBlock := ini[app+1:]
	if next := strings.Index(appBlock, "\n["); next >= 0 {
		appBlock = appBlock[:next]
	}
	if !strings.Contains(appBlock, "\nmax_blogs = 3\n") {
		t.Errorf("the blog's key belongs inside [app]:\n%s", ini)
	}

	home := files["vm/srv/chat/homeserver.yaml"]
	if !strings.Contains(home, "\nrequire_auth_for_profile_requests: true\n") {
		t.Errorf("synapse reads yaml:\n%s", home)
	}

	elem := files["home-b/srv/web/config.json"]
	if !strings.Contains(elem, "\n  \"default_theme\": \"dark\"") {
		t.Errorf("element reads json:\n%s", elem)
	}
}

// passthroughFixtureKeys is every key deployment.yaml passes through, with the
// one stack file each must reach. A clustered app renders on every apps site,
// so the file is named relative to the stack and matched on every site.
var passthroughFixtureKeys = []struct {
	app, key, needle, file string
}{
	{"talk", "KBIN_META_TITLE", "KBIN_META_TITLE", ".env"},
	{"blog", "app.max_blogs", "max_blogs", "config.ini"},
	{"chat", "require_auth_for_profile_requests", "require_auth_for_profile_requests", "homeserver.yaml"},
	{"web", "default_theme", "default_theme", "config.json"},
}

// A passthrough key reaches the kind's config file and no other: not
// compose.yaml, not a Caddy snippet, not the second .env that the blog and the
// homeserver render for their Postgres password, and not a manifest. The whole
// written tree is searched rather than a list of places it might go wrong,
// because the list is what a regression would extend.
func TestAPassthroughKeyReachesNoOtherFile(t *testing.T) {
	cfg := fixture(t)
	dir := t.TempDir()
	if err := render.Write(build(t), dir); err != nil {
		t.Fatal(err)
	}
	tree := walk(t, dir)

	for _, k := range passthroughFixtureKeys {
		if _, ok := cfg.Apps[k.app].Config[k.key]; !ok {
			t.Fatalf("the fixture no longer passes %s through on %s, so this test would check nothing", k.key, k.app)
		}
		var want []string
		if cfg.Apps[k.app].Placement.Mode == config.PlacementPinned {
			want = []string{cfg.Apps[k.app].Placement.Site + "/srv/" + k.app + "/" + k.file}
		} else {
			for _, site := range cfg.AppsSites() {
				want = append(want, site+"/srv/"+k.app+"/"+k.file)
			}
		}
		var got []string
		for path, content := range tree {
			if strings.Contains(content, k.needle) {
				got = append(got, path)
			}
		}
		sort.Strings(got)
		sort.Strings(want)
		if strings.Join(got, ",") != strings.Join(want, ",") {
			t.Errorf("%s on %s should appear in exactly %v, but appears in %v", k.key, k.app, want, got)
		}
	}
}

// The collision cannot be caught by validate, which never renders, so Build
// has to refuse it. Every command that would write the file goes through
// Build, so refusing there refuses all of them.
func TestBuildRefusesAKeyTheTemplateAlreadyWrote(t *testing.T) {
	cfg := withConfig(t, "blog", map[string]any{"database.type": "mysql"})
	_, err := render.Build(cfg, fixtureSecrets(t))
	if err == nil {
		t.Fatal("a key the template already writes must stop the build")
	}
	for _, want := range []string{
		"config-key-already-rendered",
		"apps.blog.config.database.type",
		"config.ini",
		"writefreely/config.ini.secret.tmpl",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the error should name %q, got: %v", want, err)
		}
	}
}

// A key the template leaves out on purpose is owned by the template as much as
// one it writes. Synapse writes no identity provider and no password database
// of its own, so no collision would ever catch one of those blocks coming
// back: the refusal has to know the template's decision. A path beneath the
// key is caught by its top level segment, and a name that merely starts the
// same way is not.
func TestBuildRefusesAKeyTheTemplateLeavesOutOnPurpose(t *testing.T) {
	refused := []struct {
		app, key, omitted, template string
		value                       any
	}{
		{"chat", "oidc_providers", "oidc_providers", "synapse/homeserver.yaml.secret.tmpl", "x"},
		{"chat", "oidc_config.enabled", "oidc_config", "synapse/homeserver.yaml.secret.tmpl", true},
		{"chat", "cas_config.enabled", "cas_config", "synapse/homeserver.yaml.secret.tmpl", true},
		{"chat", "saml2_config.config_path", "saml2_config", "synapse/homeserver.yaml.secret.tmpl", "/data/saml.yaml"},
		{"chat", "jwt_config.enabled", "jwt_config", "synapse/homeserver.yaml.secret.tmpl", true},
		{"chat", "password_config.enabled", "password_config", "synapse/homeserver.yaml.secret.tmpl", true},
		{"blog", "uploads.dir", "uploads.dir", "writefreely/config.ini.secret.tmpl", "/data/uploads"},
	}
	for _, tc := range refused {
		_, err := render.Build(withConfig(t, tc.app, map[string]any{tc.key: tc.value}), fixtureSecrets(t))
		if err == nil {
			t.Errorf("%s on %s: the template leaves %s out on purpose, so the build must stop", tc.key, tc.app, tc.omitted)
			continue
		}
		for _, want := range []string{
			"config-key-already-rendered",
			"apps." + tc.app + ".config." + tc.key,
			"leaves " + tc.omitted + " out of",
			"on purpose",
			tc.template,
		} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("%s on %s: the error should name %q, got: %v", tc.key, tc.app, want, err)
			}
		}
	}

	// Controls: a top level name that only starts like an omitted one, and a
	// key in the same ini section, both render. Without them the rows above
	// would pass for a rule that refused everything.
	for _, ok := range []struct{ app, key string }{
		{"chat", "oidc_providers_note"},
		{"blog", "uploads.directory_note"},
	} {
		if _, err := render.Build(withConfig(t, ok.app, map[string]any{ok.key: "x"}), fixtureSecrets(t)); err != nil {
			t.Errorf("%s on %s is not an omitted key and should render: %v", ok.key, ok.app, err)
		}
	}
}

// Where a sanctioned settings input already controls the value, the refusal
// sends the operator there, because that is the reviewable way to change it.
func TestACollisionNamesTheSettingThatOwnsTheValue(t *testing.T) {
	cfg := withConfig(t, "blog", map[string]any{"app.theme": "dark"})
	_, err := render.Build(cfg, fixtureSecrets(t))
	if err == nil {
		t.Fatal("a key the template already writes must stop the build")
	}
	for _, want := range []string{"config-key-already-rendered", "apps.blog.config.app.theme", "apps.blog.settings.theme"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the error should name %q, got: %v", want, err)
		}
	}
}

// Compose gives `environment:` precedence over `env_file`, so an env key the
// stack's compose.yaml already sets would land in .env and be silently
// shadowed. The gate's members instance sets its group under environment:,
// which is exactly where an operator reaching for this would collide.
func TestAnEnvKeyComposeAlreadySetsIsRefused(t *testing.T) {
	gate := planFiles(build(t))["home-a/srv/gate/compose.yaml"]
	if !strings.Contains(gate, "OAUTH2_PROXY_ALLOWED_GROUPS:") {
		t.Fatalf("the gate's compose.yaml no longer sets the group under environment:, so this test would check nothing:\n%s", gate)
	}

	cfg := withConfig(t, "gate", map[string]any{"OAUTH2_PROXY_ALLOWED_GROUPS": "everyone"})
	_, err := render.Build(cfg, fixtureSecrets(t))
	if err == nil {
		t.Fatal("a key compose.yaml sets under environment: must stop the build, or the .env value is silently shadowed")
	}
	for _, want := range []string{"config-key-already-rendered", "apps.gate.config.OAUTH2_PROXY_ALLOWED_GROUPS", "compose.yaml", "apps.gate.settings.members_group"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the error should name %q, got: %v", want, err)
		}
	}

	cfg = withConfig(t, "gate", map[string]any{"OAUTH2_PROXY_HTTP_ADDRESS": "0.0.0.0:9999"})
	_, err = render.Build(cfg, fixtureSecrets(t))
	if err == nil {
		t.Fatal("a key compose.yaml sets under environment: must stop the build")
	}
	for _, want := range []string{"config-key-already-rendered", "compose.yaml", "oauth2-proxy/compose.yaml.tmpl"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the error should name %q, got: %v", want, err)
		}
	}
}

// Each entry in the table of settings that own a rendered key has to be true:
// changing the setting changes the line that key is on. An entry that has gone
// stale would send an operator to a setting that does nothing.
func TestEverySettingThatOwnsAKeyReallyControlsIt(t *testing.T) {
	cfg := fixture(t)
	owners := render.SettingOwners()
	if len(owners) == 0 {
		t.Fatal("the table is empty, so this test checks nothing")
	}
	for _, o := range owners {
		var app string
		for _, name := range cfg.AppNames() {
			if cfg.Apps[name].Kind == o.Kind {
				app = name
				break
			}
		}
		if app == "" {
			t.Errorf("the fixture declares no %s app, so the entry for %s cannot be checked", o.Kind, o.Key)
			continue
		}

		line := func(value any) string {
			c := fixture(t)
			a := c.Apps[app]
			settings := map[string]any{}
			for k, v := range a.Settings {
				settings[k] = v
			}
			settings[o.Setting] = value
			a.Settings = settings
			c.Apps[app] = a
			plan, err := render.Build(c, fixtureSecrets(t))
			if err != nil {
				t.Fatalf("building with %s set: %v", o.Setting, err)
			}
			for _, f := range plan.Files {
				if !strings.HasSuffix(f.Path, "/srv/"+app+"/"+o.File) {
					continue
				}
				leaf := o.Key[strings.LastIndex(o.Key, ".")+1:]
				for _, l := range strings.Split(f.Content, "\n") {
					l = strings.TrimSpace(l)
					if strings.HasPrefix(l, leaf+"=") || strings.HasPrefix(l, leaf+" =") ||
						strings.HasPrefix(l, leaf+":") || strings.HasPrefix(l, `"`+leaf+`":`) {
						return l
					}
				}
				t.Fatalf("%s carries no line for %s", f.Path, o.Key)
			}
			t.Fatalf("no %s was rendered for %s", o.File, app)
			return ""
		}

		changed := line("owner-check-a") != line("owner-check-b") || line(true) != line(false)
		if !changed {
			t.Errorf("%s says settings.%s owns %s in %s, but changing the setting does not change that line", o.Kind, o.Setting, o.Key, o.File)
		}
	}
}

// Every way compose can take a variable from the stack's own files has to be
// seen, or the .env value a passthrough key adds is shadowed or interpolated
// somewhere nobody looked.
func TestComposeSetsSeesEveryWayComposeTakesAVariable(t *testing.T) {
	const compose = `
# KBIN_COMMENTED is only mentioned in a comment, and compose never reads one.
services:
  map:
    environment:
      MAP_FORM: "x"
  list:
    environment:
      - LIST_FORM=y
      - LIST_BARE
  interp:
    image: "postgres:${BRACED}"
    command: ["run", "$PLAIN", "${DEFAULTED:-z}", "${REQUIRED:?set}", "$$ESCAPED"]
`
	for _, key := range []string{"MAP_FORM", "LIST_FORM", "LIST_BARE", "BRACED", "PLAIN", "DEFAULTED", "REQUIRED"} {
		got, err := render.ComposeSets(compose, key)
		if err != nil {
			t.Fatal(err)
		}
		if !got {
			t.Errorf("%s is set or read by the compose file, but was not seen", key)
		}
	}
	for _, key := range []string{"MAP", "LIST", "BRACE", "PLAI", "KBIN_COMMENTED", "ESCAPED", "MAP_FORM_X"} {
		got, err := render.ComposeSets(compose, key)
		if err != nil {
			t.Fatal(err)
		}
		if got {
			t.Errorf("%s is not set or read by the compose file, but was reported", key)
		}
	}
}

// Mbin is a stack, not a container. Upstream's compose.yaml runs the web
// application beside messenger consumers, a broker behind an AMQP proxy and a
// cache, and an app container on its own starts, migrates and then cannot
// deliver a single federated activity. Every name checked here was read from
// the paisans fork at tag v1.13.3+paisans.
func TestMbinRendersItsWholeStack(t *testing.T) {
	files := planFiles(build(t))
	compose := files["home-a/srv/talk/compose.yaml"]
	env := files["home-a/srv/talk/.env"]

	for _, service := range []string{"  app:", "  messenger:", "  amqproxy:", "  rabbitmq:", "  valkey:"} {
		if !strings.Contains(compose, "\n"+service+"\n") {
			t.Errorf("the Mbin stack has no %s service:\n%s", strings.TrimSpace(service), compose)
		}
	}
	if strings.Count(compose, "ports:") != 1 {
		t.Errorf("only app may publish a port; the sidecars are reached over the project's own network:\n%s", compose)
	}

	// FrankenPHP listens plainly on the port the gateway routes to, and never
	// asks for a certificate of its own: TLS ends at the gateway.
	for _, want := range []string{`SERVER_NAME: ":8080"`, `CADDY_GLOBAL_OPTIONS: "auto_https off"`, `"10.44.0.1:8080:8080"`} {
		if !strings.Contains(compose, want) {
			t.Errorf("the app service does not carry %s:\n%s", want, compose)
		}
	}
	if strings.Contains(env, "SERVER_NAME=") {
		t.Errorf("SERVER_NAME belongs to compose.yaml, where a hostname cannot replace the plain listener:\n%s", env)
	}
	snippet := files["vm/srv/infra/caddy/snippets/talk.caddy"]
	if !strings.Contains(snippet, "10.44.0.1:8080") || !strings.Contains(snippet, "10.44.0.2:8080") {
		t.Errorf("the gateway does not route to the port the app publishes:\n%s", snippet)
	}

	for _, want := range []string{
		"\nMBIN_USER=1000:1000\n",
		"\nAPP_SECRET=fixture-not-a-secret-talk-app\n",
		"\nRABBITMQ_DEFAULT_USER=mbin\n",
		"\nRABBITMQ_DEFAULT_PASS=fixture-not-a-secret-rabbitmq\n",
		"\nMESSENGER_TRANSPORT_DSN=amqp://mbin:fixture-not-a-secret-rabbitmq@amqproxy:5673/%2f/messages\n",
		"\nVALKEY_PASSWORD=fixture-not-a-secret-valkey\n",
		"\nREDIS_DNS=redis://fixture-not-a-secret-valkey@valkey:6379\n",
		"\nMERCURE_URL=http://app:8080/.well-known/mercure\n",
		"\nMERCURE_PUBLIC_URL=https://talk.example.org/.well-known/mercure\n",
		"\nMERCURE_PUBLISHER_JWT_KEY=fixture-not-a-secret-mercure\n",
		"\nMERCURE_SUBSCRIBER_JWT_KEY=fixture-not-a-secret-mercure\n",
		"\nOAUTH_PASSPHRASE=fixture-not-a-secret-talk-oauth-passphrase\n",
		"\nOAUTH_ENCRYPTION_KEY=fixture-not-a-secret-talk-oauth-encryption\n",
		"\nS3_VERSION=latest\n",
		`CORS_ALLOW_ORIGIN='^https?://(talk\.example\.org|127\.0\.0\.1)(:[0-9]+)?$'`,
		"@10.44.0.1:5000/talk?serverVersion=18&charset=utf8\n",
	} {
		if !strings.Contains(env, want) {
			t.Errorf("the Mbin .env does not carry %q:\n%s", strings.TrimSpace(want), env)
		}
	}

	if _, ok := files["home-a/srv/talk/valkey.conf"]; !ok {
		t.Error("valkey.conf was not rendered, so the cache would run without upstream's memory limit and with snapshots on")
	}
	// The fork's docker/docker-entrypoint.sh (tag v1.13.3+paisans) runs
	// `sed -i` on these three files at every start of app and messenger, under
	// `set -e`. A bind mount over any of them makes that sed fail and the
	// container exit, so the S3 switch is left to the entrypoint, which makes
	// it whenever S3_KEY is set.
	for _, edited := range []string{"liip_imagine.yaml", "monolog.yaml", "oneup_flysystem.yaml"} {
		if strings.Contains(compose, ":/app/config/packages/"+edited) {
			t.Errorf("compose.yaml mounts over config/packages/%s, which the image's entrypoint edits in place:\n%s", edited, compose)
		}
	}
	if _, ok := files["home-a/srv/talk/config/packages/oneup_flysystem.yaml"]; ok {
		t.Error("the oneup_flysystem.yaml shim is rendered again; the image's entrypoint switches the adapter itself")
	}
	if !strings.Contains(env, "\nS3_KEY=") {
		t.Errorf("the Mbin .env does not set S3_KEY, so the entrypoint would leave uploads on local disk:\n%s", env)
	}
}

// Pinned Mbin keeps its own database beside the rest of the stack, and the
// application waits for it.
func TestPinnedMbinRunsItsOwnDatabase(t *testing.T) {
	cfg := fixture(t)
	talk := cfg.Apps["talk"]
	talk.Placement = config.Placement{Mode: config.PlacementPinned, Site: "home-b", Literal: "home-b"}
	cfg.Apps["talk"] = talk
	plan, err := render.Build(cfg, fixtureSecrets(t))
	if err != nil {
		t.Fatal(err)
	}
	files := planFiles(plan)
	compose := files["home-b/srv/talk/compose.yaml"]
	env := files["home-b/srv/talk/.env"]
	if !strings.Contains(compose, "\n  postgres:\n") {
		t.Errorf("a pinned Mbin has no postgres service:\n%s", compose)
	}
	if strings.Count(compose, "      postgres:\n        condition: service_started") != 2 {
		t.Errorf("app and messenger should both wait for the pinned database:\n%s", compose)
	}
	if !strings.Contains(env, "@postgres:5432/talk?serverVersion=18&charset=utf8\n") || !strings.Contains(env, "\nPOSTGRES_PASSWORD=") {
		t.Errorf("a pinned Mbin does not connect to its own database:\n%s", env)
	}
	if !strings.Contains(compose, `"10.44.0.2:8080:8080"`) {
		t.Errorf("a pinned Mbin does not publish on its own site's mesh address:\n%s", compose)
	}
}

// Mbin's sign in comes back to the fork's verify route, and the .env says so,
// because that comment is where an operator registering the client looks. It
// used to say /oauth/oidc/verify while the value it was built from said
// /oauth/callback, which no route in the fork serves.
func TestMbinNamesTheCallbackItServes(t *testing.T) {
	env := planFiles(build(t))["home-a/srv/talk/.env"]
	want := kinds.MbinRedirectURI("talk.example.org")
	if !strings.Contains(env, want) {
		t.Errorf("the Mbin .env does not name %s as the callback to register:\n%s", want, env)
	}
	if strings.Contains(env, "/oauth/callback") {
		t.Errorf("the Mbin .env names /oauth/callback, which the fork does not serve:\n%s", env)
	}
}

// watchdog: off is the one mode that changes what is rendered. Patroni is told
// not to want a device, and the compose file stops mapping one: compose refuses
// to create a container whose device does not exist, so leaving the mapping in
// would fail the very host that has no watchdog. Every other mode renders as
// the golden tree does, required and mapped, and only the site that declared
// off changes.
func TestWatchdogOffRendersPatroniWithoutTheDevice(t *testing.T) {
	cfg := fixture(t)
	site := cfg.Sites["home-b"]
	site.Watchdog = config.WatchdogOff
	cfg.Sites["home-b"] = site
	plan, err := render.Build(cfg, fixtureSecrets(t))
	if err != nil {
		t.Fatal(err)
	}
	files := planFiles(plan)

	if env := files["home-b/srv/infra/patroni.env"]; !strings.Contains(env, "watchdog: {mode: 'off'}") {
		t.Errorf("home-b declared watchdog off and its patroni.env says otherwise:\n%s", env)
	}
	if compose := files["home-b/srv/infra/compose.yaml"]; strings.Contains(compose, "/dev/watchdog") {
		t.Errorf("home-b declared watchdog off and its compose still maps the device:\n%s", compose)
	}
	if env := files["home-a/srv/infra/patroni.env"]; !strings.Contains(env, "watchdog: {mode: required}") {
		t.Errorf("home-a did not declare off and lost its watchdog:\n%s", env)
	}
	if compose := files["home-a/srv/infra/compose.yaml"]; !strings.Contains(compose, "- /dev/watchdog:/dev/watchdog") {
		t.Errorf("home-a did not declare off and lost its device mapping:\n%s", compose)
	}
}

// Mbin's OAuth2 keypair reaches every site that runs Mbin, as two files in the
// directory compose.yaml mounts at /app/config/oauth2, which is where the
// .env's OAUTH_PRIVATE_KEY and OAUTH_PUBLIC_KEY point.
//
// Both are 0644, the one private key this toolkit renders world readable, and
// that is deliberate. apply writes every file as root, and Mbin reads the key
// as uid 1000 after the entrypoint drops to it, so a 0600 key is a key Mbin
// cannot open. What makes 0644 acceptable is that the key is encrypted with
// OAUTH_PASSPHRASE, which is only in the 0600 .env, so the test opens it with
// exactly that value.
func TestMbinOAuthKeypairIsRenderedForEveryAppsSite(t *testing.T) {
	plan := build(t)
	files := map[string]render.File{}
	for _, f := range plan.Files {
		files[f.Path] = f
	}

	var privates []string
	for path := range files {
		if !strings.HasSuffix(path, "/srv/talk/compose.yaml") {
			continue
		}
		dir := strings.TrimSuffix(path, "compose.yaml")
		compose := files[path].Content
		for _, service := range []string{"app", "messenger"} {
			block := compose[strings.Index(compose, "\n  "+service+":\n"):]
			block = block[:strings.Index(block[1:], "\n  amqproxy:\n")+1]
			if service == "app" {
				block = block[:strings.Index(block, "\n  messenger:\n")]
			}
			if !strings.Contains(block, "/srv/talk/oauth:/app/config/oauth2:ro") {
				t.Errorf("%s: %s does not mount the keypair read only at /app/config/oauth2", path, service)
			}
		}

		private, okPrivate := files[dir+"oauth/private.pem"]
		public, okPublic := files[dir+"oauth/public.pem"]
		if !okPrivate || !okPublic {
			t.Errorf("%s has no rendered oauth/private.pem and oauth/public.pem beside it", path)
			continue
		}
		for _, f := range []render.File{private, public} {
			if f.Mode != 0o644 {
				t.Errorf("%s is %04o; uid 1000 in the container cannot read a root owned file unless it is 0644", f.Path, f.Mode)
			}
		}

		env := files[dir+".env"].Content
		var passphrase string
		for _, line := range strings.Split(env, "\n") {
			if v, ok := strings.CutPrefix(line, "OAUTH_PASSPHRASE="); ok {
				passphrase = v
			}
		}
		if !strings.Contains(private.Content, "Proc-Type: 4,ENCRYPTED") {
			t.Errorf("%s is 0644 and not encrypted", private.Path)
		}
		key, err := secretsgen.OpenOAuthPrivateKey(private.Content, passphrase)
		if err != nil {
			t.Errorf("%s does not open with the rendered OAUTH_PASSPHRASE: %v", private.Path, err)
			continue
		}
		block, _ := pem.Decode([]byte(public.Content))
		if block == nil {
			t.Errorf("%s is not PEM", public.Path)
			continue
		}
		parsed, err := x509.ParsePKIXPublicKey(block.Bytes)
		if err != nil {
			t.Errorf("%s does not parse: %v", public.Path, err)
			continue
		}
		if pub, ok := parsed.(*rsa.PublicKey); !ok || !pub.Equal(&key.PublicKey) {
			t.Errorf("%s is not the public half of %s", public.Path, private.Path)
		}
		privates = append(privates, private.Content)
	}
	if len(privates) < 2 {
		t.Fatalf("the fixture's clustered Mbin rendered a keypair on %d sites; this test needs at least two to check they agree", len(privates))
	}
	for _, p := range privates[1:] {
		if p != privates[0] {
			t.Error("two apps sites rendered different private keys, so a token one issues fails on the other")
		}
	}
}

// Spilo writes Patroni's configuration from its own variables, and it starts
// Patroni with almost no environment, so a PATRONI_* variable never arrives.
// The first real host ran with an embedded etcd, its hostname as member name,
// every listener on every interface and no watchdog, all because of that. What
// must arrive goes in Spilo's variables or in SPILO_CONFIGURATION.
func TestPatroniEnvSpeaksSpilosVocabulary(t *testing.T) {
	env := planFiles(build(t))["home-a/srv/infra/patroni.env"]
	if strings.Contains(env, "\nPATRONI_") {
		t.Errorf("patroni.env carries PATRONI_* variables, which Spilo unsets before Patroni starts:\n%s", env)
	}
	for _, want := range []string{"\nSCOPE=", "\nETCD3_HOSTS=10.44.0.", "\nPGPASSWORD_SUPERUSER=", "\nPGPASSWORD_STANDBY=", "\nPGPASSWORD_ADMIN="} {
		if !strings.Contains(env, want) {
			t.Errorf("patroni.env lacks %q:\n%s", strings.TrimSpace(want), env)
		}
	}
	var line string
	for _, l := range strings.Split(env, "\n") {
		if strings.HasPrefix(l, "SPILO_CONFIGURATION=") {
			line = strings.TrimPrefix(l, "SPILO_CONFIGURATION=")
		}
	}
	var doc struct {
		Name    string `yaml:"name"`
		RestAPI struct {
			Listen string `yaml:"listen"`
		} `yaml:"restapi"`
		PostgreSQL struct {
			Listen     string         `yaml:"listen"`
			Parameters map[string]any `yaml:"parameters"`
		} `yaml:"postgresql"`
		Watchdog struct {
			Mode string `yaml:"mode"`
		} `yaml:"watchdog"`
		Bootstrap struct {
			DCS map[string]any `yaml:"dcs"`
		} `yaml:"bootstrap"`
	}
	if err := yaml.Unmarshal([]byte(line), &doc); err != nil {
		t.Fatalf("SPILO_CONFIGURATION is not YAML: %v\n%s", err, line)
	}
	if doc.Name != "home-a" {
		t.Errorf("the member name is %q, not the site's name, so apply cannot find the leader", doc.Name)
	}
	if doc.RestAPI.Listen != "10.44.0.1:8008" || doc.PostgreSQL.Listen != "10.44.0.1,127.0.0.1:5432" {
		t.Errorf("listeners are not pinned to the mesh: %+v", doc)
	}
	if doc.PostgreSQL.Parameters["bg_mon.port"] != 8009 {
		t.Errorf("bg_mon is left on 8080, where applications publish: %v", doc.PostgreSQL.Parameters)
	}
	if doc.Watchdog.Mode != "required" {
		t.Errorf("watchdog mode is %q", doc.Watchdog.Mode)
	}
	if doc.Bootstrap.DCS["synchronous_mode"] != true {
		t.Errorf("synchronous_mode did not reach the bootstrap DCS: %v", doc.Bootstrap.DCS)
	}
}
