package render_test

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/josephquigley/paisans-stack/internal/config"
	"github.com/josephquigley/paisans-stack/internal/render"
)

var update = flag.Bool("update", false, "rewrite the golden tree from the current output")

func build(t *testing.T) *render.Plan {
	t.Helper()
	cfg, err := config.Load(filepath.Join("testdata", "deployment.yaml"))
	if err != nil {
		t.Fatalf("loading the fixture configuration: %v", err)
	}
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatalf("loading the fixture secrets: %v", err)
	}
	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatalf("building the plan: %v", err)
	}
	return plan
}

// The golden tree is the specification of what an operator receives. A diff
// here is a change in what lands on a host, so it is reviewed rather than
// regenerated by reflex.
func TestGoldenTree(t *testing.T) {
	plan := build(t)
	golden := filepath.Join("testdata", "golden")

	if *update {
		if err := os.RemoveAll(golden); err != nil {
			t.Fatal(err)
		}
		if err := render.Write(plan, golden); err != nil {
			t.Fatal(err)
		}
		t.Log("golden tree rewritten")
		return
	}

	dir := t.TempDir()
	if err := render.Write(plan, dir); err != nil {
		t.Fatal(err)
	}
	compareTrees(t, golden, dir)
}

// Determinism is not a nicety: rendering twice must produce byte identical
// output, or a diff between two renders says nothing about what changed.
func TestRenderIsDeterministic(t *testing.T) {
	first, second := t.TempDir(), t.TempDir()
	if err := render.Write(build(t), first); err != nil {
		t.Fatal(err)
	}
	if err := render.Write(build(t), second); err != nil {
		t.Fatal(err)
	}
	compareTrees(t, first, second)
}

// A clustered app connects to the local proxy and has no Postgres of its own.
// A pinned app is pinned all the way down: its own database, at its own site.
func TestPlacementShapesTheStack(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}

	clustered, ok := files["home-a/srv/talk/compose.yaml"]
	if !ok {
		t.Fatal("the clustered app was not rendered onto an apps site")
	}
	if strings.Contains(clustered, "postgres:") {
		t.Error("a clustered app was given a Postgres service of its own")
	}
	env := files["home-a/srv/talk/.env"]
	if !strings.Contains(env, "@127.0.0.1:5000/") {
		t.Errorf("a clustered app does not connect to the local proxy:\n%s", env)
	}

	pinned, ok := files["vm/srv/chat/compose.yaml"]
	if !ok {
		t.Fatal("the pinned app was not rendered at its site")
	}
	if !strings.Contains(pinned, "postgres:") {
		t.Error("a pinned app was not given its own Postgres")
	}
	if _, ok := files["home-a/srv/chat/compose.yaml"]; ok {
		t.Error("a pinned app was rendered somewhere other than its site")
	}
	if !strings.Contains(pinned, "/srv/chat/postgres:/var/lib/postgresql/data") {
		t.Error("a pinned stack does not use bind mounts under /srv")
	}
}

// Trusted proxies are the mesh subnet and never a host address, which is what
// lets the gateway role move later without breaking client address handling.
func TestTrustedProxiesAreTheMeshSubnet(t *testing.T) {
	for _, f := range build(t).Files {
		if !strings.HasSuffix(f.Path, "/.env") {
			continue
		}
		if !strings.Contains(f.Content, "TRUSTED_PROXIES=10.44.0.0/24") {
			t.Errorf("%s does not trust the mesh subnet:\n%s", f.Path, f.Content)
		}
		for _, address := range []string{"TRUSTED_PROXIES=10.44.0.1", "TRUSTED_PROXIES=10.44.0.2", "TRUSTED_PROXIES=10.44.0.3"} {
			if strings.Contains(f.Content, address) {
				t.Errorf("%s trusts a specific host", f.Path)
			}
		}
	}
}

// No named volumes anywhere: a stack under /srv relocates with one tar.
func TestNoNamedVolumes(t *testing.T) {
	for _, f := range build(t).Files {
		if !strings.HasSuffix(f.Path, "compose.yaml") {
			continue
		}
		inVolumes := false
		for _, line := range strings.Split(f.Content, "\n") {
			trimmed := strings.TrimSpace(line)
			if trimmed == "volumes:" {
				if !strings.HasPrefix(line, " ") {
					t.Errorf("%s declares a top level volumes block, which is what named volumes look like", f.Path)
				}
				inVolumes = true
				continue
			}
			if !strings.HasPrefix(trimmed, "- ") {
				inVolumes = false
				continue
			}
			if !inVolumes {
				continue
			}
			mount := strings.TrimPrefix(trimmed, "- ")
			if !strings.HasPrefix(mount, "/srv/") && !strings.HasPrefix(mount, "/dev/") {
				t.Errorf("%s mounts something that is not a bind mount under /srv: %s", f.Path, mount)
			}
		}
	}
}

// DNS-01 for every hostname, so a gateway can hold valid certificates before
// any DNS record points at it. That is what makes moving the gateway an
// overlap rather than a cutover.
func TestGatewayUsesDNSChallenge(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}
	caddyfile, ok := files["vm/srv/infra/caddy/Caddyfile"]
	if !ok {
		t.Fatal("no Caddyfile was rendered for the gateway")
	}
	if !strings.Contains(caddyfile, "acme_dns cloudflare") {
		t.Errorf("the gateway does not use DNS-01:\n%s", caddyfile)
	}
	if _, ok := files["vm/srv/infra/caddy/caddy.env"]; !ok {
		t.Error("the DNS provider token was not rendered for the gateway")
	}
	for path := range files {
		if strings.HasSuffix(path, "caddy.env") && !strings.HasPrefix(path, "vm/") {
			t.Errorf("%s holds the zone token on a site that is not the gateway", path)
		}
	}
}

// Every app has its own database credential. A shared one reads every other
// app's data, since one cluster holds them all.
func TestEachAppHasItsOwnDatabasePassword(t *testing.T) {
	seen := map[string]string{}
	for _, f := range build(t).Files {
		if !strings.HasSuffix(f.Path, "/.env") {
			continue
		}
		parts := strings.Split(f.Path, "/")
		app := parts[len(parts)-2]
		for _, line := range strings.Split(f.Content, "\n") {
			if !strings.Contains(line, "fixture-not-a-secret-") || !strings.Contains(line, "-db") {
				continue
			}
			value := line[strings.Index(line, "fixture-not-a-secret-"):]
			if previous, ok := seen[value]; ok && previous != app {
				t.Errorf("%s and %s share a database credential", previous, app)
			}
			seen[value] = app
		}
	}
	if len(seen) < 4 {
		t.Fatalf("expected a distinct credential per app, found %d", len(seen))
	}
	if strings.Contains(strings.Join(keys(seen), " "), "admin") {
		t.Error("an app was given the cluster admin password")
	}
}

func keys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

// The manifest is what lets a later apply tell an untouched artifact from one
// somebody edited on the host.
func TestManifestCoversEveryFile(t *testing.T) {
	dir := t.TempDir()
	plan := build(t)
	if err := render.Write(plan, dir); err != nil {
		t.Fatal(err)
	}
	for _, site := range []string{"home-a", "home-b", "vm"} {
		data, err := os.ReadFile(filepath.Join(dir, site, render.ManifestName))
		if err != nil {
			t.Fatalf("reading the manifest for %s: %v", site, err)
		}
		for _, f := range plan.Files {
			prefix := site + "/"
			if !strings.HasPrefix(f.Path, prefix) {
				continue
			}
			if !strings.Contains(string(data), strings.TrimPrefix(f.Path, prefix)) {
				t.Errorf("%s is missing from %s's manifest", f.Path, site)
			}
		}
	}
}

func compareTrees(t *testing.T, want, got string) {
	t.Helper()
	wantFiles := walk(t, want)
	gotFiles := walk(t, got)

	for path, content := range wantFiles {
		other, ok := gotFiles[path]
		if !ok {
			t.Errorf("%s is missing from the rendered tree", path)
			continue
		}
		if content != other {
			t.Errorf("%s differs.\nwant:\n%s\ngot:\n%s", path, content, other)
		}
	}
	for path := range gotFiles {
		if _, ok := wantFiles[path]; !ok {
			t.Errorf("%s was rendered but is not in the golden tree", path)
		}
	}
}

func walk(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(rel)] = string(data)
		return nil
	})
	if err != nil {
		t.Fatalf("walking %s: %v", root, err)
	}
	return out
}
