package render_test

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/paisans-software/paisans-stack/internal/acme"
	"github.com/paisans-software/paisans-stack/internal/config"
	"github.com/paisans-software/paisans-stack/internal/kinds"
	"github.com/paisans-software/paisans-stack/internal/render"
	"github.com/paisans-software/paisans-stack/internal/validate"
)

var update = flag.Bool("update", false, "rewrite the golden tree from the current output")

// fixture loads the deployment every test in this file renders, and refuses to
// hand it back if the toolkit would not accept it.
//
// This is not belt and braces. Build does not validate, so for six tasks the
// fixture declared two apps under cluster placement that
// cluster-placement-without-a-cluster refuses outright, and the golden tree
// grew routing for a shape `paisans apply` would never have produced. A golden
// file is only a specification of what an operator receives if the input is
// something an operator could have written, so the check belongs here, ahead of
// every test, rather than in one test somebody might not run.
func fixture(t *testing.T) *config.Config {
	t.Helper()
	cfg, err := config.Load(filepath.Join("testdata", "deployment.yaml"))
	if err != nil {
		t.Fatalf("loading the fixture configuration: %v", err)
	}
	if refusals := validate.Check(cfg).Refusals(); len(refusals) > 0 {
		for _, f := range refusals {
			t.Errorf("the fixture is a configuration the toolkit refuses:\n%s", f)
		}
		t.FailNow()
	}
	return cfg
}

func build(t *testing.T) *render.Plan {
	t.Helper()
	cfg := fixture(t)
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatalf("loading the fixture secrets: %v", err)
	}
	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatalf("building the plan: %v", err)
	}
	return plan
}

// The golden tree is the specification of what an operator receives. A diff
// here is a change in what lands on a host, so it is reviewed rather than
// regenerated by reflex.
func TestGoldenTree(t *testing.T) {
	plan := build(t)
	golden := filepath.Join("testdata", "golden")

	if *update {
		if err := os.RemoveAll(golden); err != nil {
			t.Fatal(err)
		}
		if err := render.Write(plan, golden); err != nil {
			t.Fatal(err)
		}
		t.Log("golden tree rewritten")
		return
	}

	dir := t.TempDir()
	if err := render.Write(plan, dir); err != nil {
		t.Fatal(err)
	}
	compareTrees(t, golden, dir)
}

// Determinism is not a nicety: rendering twice must produce byte identical
// output, or a diff between two renders says nothing about what changed.
func TestRenderIsDeterministic(t *testing.T) {
	first, second := t.TempDir(), t.TempDir()
	if err := render.Write(build(t), first); err != nil {
		t.Fatal(err)
	}
	if err := render.Write(build(t), second); err != nil {
		t.Fatal(err)
	}
	compareTrees(t, first, second)
}

// A clustered app connects to the local proxy and has no Postgres of its own.
// A pinned app is pinned all the way down: its own database, at its own site.
func TestPlacementShapesTheStack(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}

	clustered, ok := files["home-a/srv/talk/compose.yaml"]
	if !ok {
		t.Fatal("the clustered app was not rendered onto an apps site")
	}
	if strings.Contains(clustered, "postgres:") {
		t.Error("a clustered app was given a Postgres service of its own")
	}
	env := files["home-a/srv/talk/.env"]
	if !strings.Contains(env, "@127.0.0.1:5000/") {
		t.Errorf("a clustered app does not connect to the local proxy:\n%s", env)
	}

	pinned, ok := files["vm/srv/chat/compose.yaml"]
	if !ok {
		t.Fatal("the pinned app was not rendered at its site")
	}
	if !strings.Contains(pinned, "postgres:") {
		t.Error("a pinned app was not given its own Postgres")
	}
	if _, ok := files["home-a/srv/chat/compose.yaml"]; ok {
		t.Error("a pinned app was rendered somewhere other than its site")
	}
	if !strings.Contains(pinned, "/srv/chat/postgres:/var/lib/postgresql/data") {
		t.Error("a pinned stack does not use bind mounts under /srv")
	}
}

// A declared image reaches the compose file, and a service nobody declared
// takes the default its kind ships. Both halves matter: the first is what makes
// running a fork a config edit, and the second is what an adopter who never
// opens the stanza receives.
func TestDeclaredImagesWinAndDefaultsFillIn(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}

	talk := files["home-a/srv/talk/compose.yaml"]
	if !strings.Contains(talk, "image: ghcr.io/example-org/mbin:v1.10.1-fork") {
		t.Errorf("the declared image did not reach the compose file:\n%s", talk)
	}

	docs := files["home-a/srv/docs/compose.yaml"]
	fallback, ok := kinds.DefaultImage(config.KindOutline, "app")
	if !ok {
		t.Fatal("outline ships no default image")
	}
	if !strings.Contains(docs, "image: "+fallback) {
		t.Errorf("an app that declared no image did not take its kind default %q:\n%s", fallback, docs)
	}

	// A pinned app may choose its own database image; a clustered one has no
	// database service to choose for.
	chat := files["vm/srv/chat/compose.yaml"]
	if !strings.Contains(chat, "image: postgres:17-alpine") {
		t.Errorf("a pinned app's declared database image was not used:\n%s", chat)
	}
}

// Nothing the toolkit renders may carry a floating tag. A default that failed
// its own validation rule would be the toolkit refusing configuration it wrote
// itself.
func TestRenderedImagesArePinned(t *testing.T) {
	for _, f := range build(t).Files {
		if !strings.HasSuffix(f.Path, "compose.yaml") {
			continue
		}
		for _, line := range strings.Split(f.Content, "\n") {
			line = strings.TrimSpace(line)
			if !strings.HasPrefix(line, "image: ") {
				continue
			}
			ref := strings.TrimPrefix(line, "image: ")
			if strings.Contains(ref, "{{") || strings.Contains(ref, "$") {
				continue
			}
			if !kinds.ParseReference(ref).Pinned() {
				t.Errorf("%s renders %q, which does not name one build", f.Path, ref)
			}
		}
	}
}

// Not every application is configured by environment variables, and a design
// that can only render an .env cannot configure two of the five kinds here.
// WriteFreely reads an INI file and Synapse reads homeserver.yaml, and both
// carry credentials, so both must be rendered and both must be 0600.
func TestTemplateSetsRenderEachKindsOwnFiles(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	cases := []struct {
		path    string
		mode    uint32
		carries string
	}{
		{"home-a/srv/blog/config.ini", 0o600, "type = sqlite3"},
		{"vm/srv/chat/homeserver.yaml", 0o600, "name: psycopg2"},
		{"home-a/srv/talk/.env", 0o600, "DATABASE_URL="},
		{"home-a/srv/talk/compose.yaml", 0o644, "name: paisans-talk"},
		// A template's path is its destination, nested directories included.
		{"home-a/srv/talk/config/packages/oneup_flysystem.yaml", 0o644, "kbin.s3_adapter"},
	}
	for _, tc := range cases {
		f, ok := files[tc.path]
		if !ok {
			t.Errorf("%s was not rendered", tc.path)
			continue
		}
		if f.Mode != tc.mode {
			t.Errorf("%s rendered %04o, want %04o", tc.path, f.Mode, tc.mode)
		}
		if !strings.Contains(f.Content, tc.carries) {
			t.Errorf("%s does not contain %q:\n%s", tc.path, tc.carries, f.Content)
		}
	}

	// The blog has no Postgres anywhere: no service, no role, no connection
	// string. A configuration pointing it at the cluster would be a lie.
	for path, f := range files {
		if !strings.HasPrefix(path, "home-a/srv/blog/") {
			continue
		}
		if strings.Contains(f.Content, "postgresql://") {
			t.Errorf("%s hands WriteFreely a Postgres connection, which it has never supported:\n%s", path, f.Content)
		}
	}
}

// A secret in a bind mounted file is not visible through `docker inspect` or
// /proc/<pid>/environ, which is the reason a file configured application is the
// better case rather than the awkward one. That only holds if the file is 0600.
func TestEverySecretBearingFileIs0600(t *testing.T) {
	needles := []string{"fixture-not-a-secret", "client-secret"}
	for _, f := range build(t).Files {
		carries := false
		for _, needle := range needles {
			if strings.Contains(f.Content, needle) {
				carries = true
			}
		}
		if carries && f.Mode != 0o600 {
			t.Errorf("%s carries a credential and is %04o, not 0600", f.Path, f.Mode)
		}
	}
}

// Routing is assembled from per kind snippets rather than written into one
// file that knows every kind. The gateway keeps what is cross cutting; each app
// brings its own block, wherever it runs.
func TestTheGatewayImportsEachAppsOwnSnippet(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	caddyfile, ok := files["vm/srv/infra/caddy/Caddyfile"]
	if !ok {
		t.Fatal("the gateway rendered no Caddyfile")
	}
	for _, app := range []string{"talk", "docs", "auth", "blog", "chat"} {
		snippet := "vm/srv/infra/caddy/snippets/" + app + ".caddy"
		if _, ok := files[snippet]; !ok {
			t.Errorf("%s was not rendered onto the gateway", snippet)
		}
		if !strings.Contains(caddyfile.Content, "import /etc/caddy/snippets/"+app+".caddy") {
			t.Errorf("the Caddyfile does not import %s's snippet:\n%s", app, caddyfile.Content)
		}
	}

	// The gateway holds no application specific routing of its own. A proxy
	// directive here would be the conditional file this design rejects,
	// growing with every application added.
	if strings.Contains(caddyfile.Content, "reverse_proxy") {
		t.Errorf("the gateway file routes an application itself:\n%s", caddyfile.Content)
	}

	// A snippet is rendered onto the gateway, never into the app's own
	// directory, because that is not where it is read.
	for path := range files {
		if strings.HasSuffix(path, "caddy.snippet") || strings.Contains(path, "/srv/talk/caddy") {
			t.Errorf("%s put an app's routing beside the app", path)
		}
	}

	// A snippet never hardcodes where its app runs: a pinned app gets one
	// upstream and a clustered one gets every apps site, both from inventory.
	pinned := files["vm/srv/infra/caddy/snippets/chat.caddy"].Content
	if !strings.Contains(pinned, "10.44.0.3:8008") {
		t.Errorf("a pinned app's snippet does not point at its site:\n%s", pinned)
	}
	clustered := files["vm/srv/infra/caddy/snippets/talk.caddy"].Content
	if !strings.Contains(clustered, "10.44.0.1:8080 10.44.0.2:8080") {
		t.Errorf("a clustered app's snippet does not point at both apps sites:\n%s", clustered)
	}
}

// Trusted proxies are the mesh subnet and never a host address, which is what
// lets the gateway role move later without breaking client address handling.
func TestTrustedProxiesAreTheMeshSubnet(t *testing.T) {
	// Not every kind takes a trusted proxy setting, and one of those that does
	// is not configured by environment at all, so the assertion is about every
	// rendered file that mentions one rather than about `.env` files.
	var saw int
	for _, f := range build(t).Files {
		if !strings.Contains(f.Content, "TRUSTED_PROXIES") {
			continue
		}
		saw++
		if !strings.Contains(f.Content, "TRUSTED_PROXIES=10.44.0.0/24") {
			t.Errorf("%s does not trust the mesh subnet:\n%s", f.Path, f.Content)
		}
		for _, address := range []string{"TRUSTED_PROXIES=10.44.0.1", "TRUSTED_PROXIES=10.44.0.2", "TRUSTED_PROXIES=10.44.0.3"} {
			if strings.Contains(f.Content, address) {
				t.Errorf("%s trusts a specific host", f.Path)
			}
		}
	}
	if saw == 0 {
		t.Fatal("no rendered file set a trusted proxy, so this proved nothing")
	}
}

// The mesh subnet is whatever the file declares, not a constant in the code.
// It reaches both the trusted proxy list and the WireGuard interface address.
func TestMeshSubnetComesFromTheConfiguration(t *testing.T) {
	cfg := fixture(t)
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	cfg.Mesh.Subnet = "10.77.0.0/16"
	for name, site := range cfg.Sites {
		site.Address = strings.Replace(site.Address, "10.44.0.", "10.77.0.", 1)
		cfg.Sites[name] = site
	}
	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatal(err)
	}
	var sawEnv, sawInterface bool
	for _, f := range plan.Files {
		if strings.Contains(f.Content, "TRUSTED_PROXIES") {
			sawEnv = true
			if !strings.Contains(f.Content, "TRUSTED_PROXIES=10.77.0.0/16") {
				t.Errorf("%s did not follow the declared mesh:\n%s", f.Path, f.Content)
			}
		}
		if strings.HasSuffix(f.Path, "wg0.conf") {
			sawInterface = true
			if !strings.Contains(f.Content, "/16\n") {
				t.Errorf("%s did not use the declared prefix length:\n%s", f.Path, f.Content)
			}
		}
	}
	if !sawEnv || !sawInterface {
		t.Fatal("the test did not reach the files it checks")
	}
}

// No named volumes anywhere: a stack under /srv relocates with one tar.
func TestNoNamedVolumes(t *testing.T) {
	for _, f := range build(t).Files {
		if !strings.HasSuffix(f.Path, "compose.yaml") {
			continue
		}
		inVolumes := false
		for _, line := range strings.Split(f.Content, "\n") {
			trimmed := strings.TrimSpace(line)
			if trimmed == "volumes:" {
				if !strings.HasPrefix(line, " ") {
					t.Errorf("%s declares a top level volumes block, which is what named volumes look like", f.Path)
				}
				inVolumes = true
				continue
			}
			if !strings.HasPrefix(trimmed, "- ") {
				inVolumes = false
				continue
			}
			if !inVolumes {
				continue
			}
			mount := strings.TrimPrefix(trimmed, "- ")
			if !strings.HasPrefix(mount, "/srv/") && !strings.HasPrefix(mount, "/dev/") {
				t.Errorf("%s mounts something that is not a bind mount under /srv: %s", f.Path, mount)
			}
		}
	}
}

// DNS-01 for every hostname, so a gateway can hold valid certificates before
// any DNS record points at it. That is what makes moving the gateway an
// overlap rather than a cutover.
func TestGatewayUsesDNSChallenge(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}
	caddyfile, ok := files["vm/srv/infra/caddy/Caddyfile"]
	if !ok {
		t.Fatal("no Caddyfile was rendered for the gateway")
	}
	if !strings.Contains(caddyfile, "acme_dns desec") {
		t.Errorf("the gateway does not use DNS-01:\n%s", caddyfile)
	}
	if _, ok := files["vm/srv/infra/caddy/caddy.env"]; !ok {
		t.Error("the DNS provider token was not rendered for the gateway")
	}
	for path := range files {
		if strings.HasSuffix(path, "caddy.env") && !strings.HasPrefix(path, "vm/") {
			t.Errorf("%s holds the zone token on a site that is not the gateway", path)
		}
	}
}

// Every app has its own database credential. A shared one reads every other
// app's data, since one cluster holds them all.
func TestEachAppHasItsOwnDatabasePassword(t *testing.T) {
	seen := map[string]string{}
	for _, f := range build(t).Files {
		if !strings.HasSuffix(f.Path, "/.env") {
			continue
		}
		parts := strings.Split(f.Path, "/")
		app := parts[len(parts)-2]
		for _, line := range strings.Split(f.Content, "\n") {
			if !strings.Contains(line, "fixture-not-a-secret-") || !strings.Contains(line, "-db") {
				continue
			}
			value := line[strings.Index(line, "fixture-not-a-secret-"):]
			if previous, ok := seen[value]; ok && previous != app {
				t.Errorf("%s and %s share a database credential", previous, app)
			}
			seen[value] = app
		}
	}
	if len(seen) < 4 {
		t.Fatalf("expected a distinct credential per app, found %d", len(seen))
	}
	if strings.Contains(strings.Join(keys(seen), " "), "admin") {
		t.Error("an app was given the cluster admin password")
	}
}

func keys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

// The manifest is what lets a later apply tell an untouched artifact from one
// somebody edited on the host.
func TestManifestCoversEveryFile(t *testing.T) {
	dir := t.TempDir()
	plan := build(t)
	if err := render.Write(plan, dir); err != nil {
		t.Fatal(err)
	}
	for _, site := range []string{"home-a", "home-b", "vm"} {
		data, err := os.ReadFile(filepath.Join(dir, site, render.ManifestName))
		if err != nil {
			t.Fatalf("reading the manifest for %s: %v", site, err)
		}
		for _, f := range plan.Files {
			prefix := site + "/"
			if !strings.HasPrefix(f.Path, prefix) {
				continue
			}
			if !strings.Contains(string(data), strings.TrimPrefix(f.Path, prefix)) {
				t.Errorf("%s is missing from %s's manifest", f.Path, site)
			}
		}
	}
}

func compareTrees(t *testing.T, want, got string) {
	t.Helper()
	wantFiles := walk(t, want)
	gotFiles := walk(t, got)

	for path, content := range wantFiles {
		other, ok := gotFiles[path]
		if !ok {
			t.Errorf("%s is missing from the rendered tree", path)
			continue
		}
		if content != other {
			t.Errorf("%s differs.\nwant:\n%s\ngot:\n%s", path, content, other)
		}
	}
	for path := range gotFiles {
		if _, ok := wantFiles[path]; !ok {
			t.Errorf("%s was rendered but is not in the golden tree", path)
		}
	}
}

func walk(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(rel)] = string(data)
		return nil
	})
	if err != nil {
		t.Fatalf("walking %s: %v", root, err)
	}
	return out
}

// Every template a kind ships has to be committed, and the templates that
// render an .env are the ones at risk: the repository ignores `.env.*` so that
// no real credential is ever committed, and the four files named
// `.env.secret.tmpl` match that rule by accident.
//
// The failure mode is why this test exists rather than a comment. The files
// stay on the machine that wrote them, where every test passes, and a fresh
// checkout renders a stack with no environment at all. Reading the embedded
// filesystem catches it, because embed sees exactly what git checked out.
func TestEveryKindShipsACommittedTemplateSet(t *testing.T) {
	for _, kind := range []config.Kind{
		config.KindMbin, config.KindOutline, config.KindPocketID,
		config.KindSynapse, config.KindWriteFreely,
	} {
		files, err := render.TemplateSet(kind)
		if err != nil {
			t.Errorf("%s: %v", kind, err)
			continue
		}
		var compose, config bool
		for _, name := range files {
			switch {
			case strings.HasSuffix(name, "compose.yaml.tmpl"):
				compose = true
			case strings.HasSuffix(name, ".env.secret.tmpl"),
				strings.HasSuffix(name, "config.ini.secret.tmpl"),
				strings.HasSuffix(name, "homeserver.yaml.secret.tmpl"):
				config = true
			}
		}
		if !compose {
			t.Errorf("%s ships no compose template", kind)
		}
		if !config {
			t.Errorf("%s ships no configuration template, so the stack would start unconfigured. Check that it is committed: the repository ignores .env.*", kind)
		}
	}
}

// The provider reaches the gateway's configuration, and the credential is named
// for what it is rather than for whoever issues it.
func TestTheDeclaredProviderIsRendered(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}

	caddyfile := files["vm/srv/infra/caddy/Caddyfile"]
	if !strings.Contains(caddyfile, "acme_dns desec {") {
		t.Errorf("the gateway does not use the declared provider:\n%s", caddyfile)
	}
	if !strings.Contains(caddyfile, "token {env.ACME_DNS_TOKEN}") {
		t.Errorf("the gateway does not pass the credential to desec's block form:\n%s", caddyfile)
	}
	if strings.Contains(caddyfile, "cloudflare") {
		t.Errorf("a provider nobody declared appears in the gateway config:\n%s", caddyfile)
	}

	env := files["vm/srv/infra/caddy/caddy.env"]
	if !strings.Contains(env, "ACME_DNS_TOKEN=") {
		t.Errorf("the credential is not rendered under a provider neutral name:\n%s", env)
	}
	if strings.Contains(env, "CLOUDFLARE") {
		t.Errorf("a provider's name survives in the environment:\n%s", env)
	}
}

// The image a gateway runs is the one that carries the declared provider's
// module, pinned by digest, and never upstream's own image.
func TestTheGatewayRunsAnImageWithTheModule(t *testing.T) {
	files := map[string]string{}
	for _, f := range build(t).Files {
		files[f.Path] = f.Content
	}
	infra := files["vm/srv/infra/compose.yaml"]
	want, ok := acme.Image("desec")
	if !ok {
		t.Fatal("desec has no published image")
	}
	if !strings.Contains(infra, "image: "+want) {
		t.Errorf("the gateway does not run the image carrying its provider:\n%s", infra)
	}
	if strings.Contains(infra, "image: caddy:") {
		t.Errorf("the gateway runs upstream's image, which carries no DNS module:\n%s", infra)
	}
}

// The escape hatch has to actually work: a declared image is what keeps a
// provider the toolkit publishes nothing for from being lock-in, and it is
// worth nothing unless it reaches the gateway's compose file in place of the
// published one.
func TestADeclaredImageReachesTheGateway(t *testing.T) {
	cfg := fixture(t)
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	// A provider the toolkit publishes no image for, with the adopter's own
	// image carrying its module. This is the configuration README calls the
	// anti lock-in path.
	cfg.ACME.Provider = "route53"
	cfg.ACME.Image = "ghcr.io/example-org/caddy-route53:2.11.4"

	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatalf("a declared image and an unpublished provider failed to render: %v", err)
	}
	files := map[string]string{}
	for _, f := range plan.Files {
		files[f.Path] = f.Content
	}

	infra := files["vm/srv/infra/compose.yaml"]
	if !strings.Contains(infra, "image: "+cfg.ACME.Image) {
		t.Errorf("the gateway does not run the declared image:\n%s", infra)
	}
	published, _ := acme.Image("desec")
	if strings.Contains(infra, published) {
		t.Errorf("the published image survived a declared one:\n%s", infra)
	}
	if caddyfile := files["vm/srv/infra/caddy/Caddyfile"]; !strings.Contains(caddyfile, "acme_dns route53") {
		t.Errorf("an unpublished provider does not reach the directive:\n%s", caddyfile)
	}
}

// A deployment with no gateway site is legitimate: internal/config requires
// acme.provider only when a site holds the gateway role. The renderer must not
// demand a Caddy image for a site that will never run Caddy, or a config that
// validation accepts fails to render anyway, over an image nothing needs.
func TestNoGatewayNeedsNoACMEProvider(t *testing.T) {
	cfg := fixture(t)
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	cfg.ACME = config.ACME{}
	vm := cfg.Sites["vm"]
	vm.Roles = []config.Role{config.RoleWitness}
	cfg.Sites["vm"] = vm

	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatalf("a deployment with no gateway site failed to render: %v", err)
	}
	for _, f := range plan.Files {
		if strings.HasSuffix(f.Path, "caddy/Caddyfile") {
			t.Errorf("%s was rendered although no site holds the gateway role", f.Path)
		}
	}
}

// Element is a static web client: no database, no secrets of its own, and a
// runtime configuration naming the homeserver it talks to.
func TestElementRendersAClientConfig(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	compose, ok := files["home-b/srv/web/compose.yaml"]
	if !ok {
		t.Fatal("the element app was not rendered")
	}
	if strings.Contains(compose.Content, "postgres") {
		t.Error("element was given a database, and it has no state at all")
	}

	config, ok := files["home-b/srv/web/config.json"]
	if !ok {
		t.Fatal("element rendered no runtime configuration")
	}
	if !strings.Contains(config.Content, `"base_url": "https://chat.example.org"`) {
		t.Errorf("element's config does not name its homeserver:\n%s", config.Content)
	}
	// base_url is where the API is; server_name is the part after the colon in
	// a user identifier. They are different names whenever delegation is in
	// use, and a client that offers the wrong one offers accounts that do not
	// exist. It must be the same value the homeserver was given.
	homeserver := files["vm/srv/chat/homeserver.yaml"].Content
	if !strings.Contains(homeserver, `server_name: "example.org"`) {
		t.Fatalf("the fixture homeserver's server_name is not what this test assumes:\n%s", homeserver)
	}
	if !strings.Contains(config.Content, `"server_name": "example.org"`) {
		t.Errorf("element and the homeserver disagree about server_name:\n%s", config.Content)
	}
	if config.Mode != 0o644 {
		t.Errorf("element's config is %04o; it carries no secret and wants 0644", config.Mode)
	}
}

// One app can answer on several hostnames, and each gets its own routing. The
// case that forces it: a Matrix homeserver serves its API on one name and its
// .well-known delegation on the apex, and those are not the same routing.
func TestAnAppCanHoldSeveralHostnames(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	caddyfile, ok := files["vm/srv/infra/caddy/Caddyfile"]
	if !ok {
		t.Fatal("no gateway configuration was rendered")
	}
	for _, hostname := range []string{"chat.example.org", "example.org"} {
		if !strings.Contains(caddyfile.Content, "\n"+hostname+" {") {
			t.Errorf("the gateway has no host block for %s:\n%s", hostname, caddyfile.Content)
		}
	}

	// Each hostname imports its own snippet, because the apex serves only the
	// delegation documents while the primary serves the whole API.
	if _, ok := files["vm/srv/infra/caddy/snippets/chat.caddy"]; !ok {
		t.Error("the primary hostname has no snippet")
	}
	if _, ok := files["vm/srv/infra/caddy/snippets/chat-wellknown.caddy"]; !ok {
		t.Error("the extra hostname has no snippet of its own")
	}
}

// The gate is two instances, not one: a visitor who has authenticated is not
// yet a member, and the two are allowed to reach different applications.
func TestTheAuthGateRendersBothInstances(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	compose, ok := files["home-a/srv/gate/compose.yaml"]
	if !ok {
		t.Fatal("the gate was not rendered")
	}
	for _, service := range []string{"provisional:", "members:"} {
		if !strings.Contains(compose.Content, service) {
			t.Errorf("the gate is missing its %s instance:\n%s", service, compose.Content)
		}
	}

	env, ok := files["home-a/srv/gate/.env"]
	if !ok {
		t.Fatal("the gate rendered no environment")
	}
	if env.Mode != 0o600 {
		t.Errorf("the gate's environment is %04o and it carries a client secret", env.Mode)
	}
	if !strings.Contains(env.Content, "OIDC_ISSUER_URL=https://id.example.org") {
		t.Errorf("the gate does not point at the identity provider:\n%s", env.Content)
	}
}

// gate_provisional and gate_members are named snippets, not a hostname's
// routing: nothing imports this file by path, and they must be defined before
// anything can import them by name.
func TestTheAuthGateShipsNamedSnippets(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	gates, ok := files["vm/srv/infra/caddy/snippets/gate-gates.caddy"]
	if !ok {
		t.Fatal("the gate's named snippets were not rendered onto the gateway")
	}
	for _, name := range []string{"(gate_provisional)", "(gate_members)"} {
		if !strings.Contains(gates.Content, name) {
			t.Errorf("the gate's snippet file does not define %s:\n%s", name, gates.Content)
		}
	}

	caddyfile, ok := files["vm/srv/infra/caddy/Caddyfile"]
	if !ok {
		t.Fatal("no gateway configuration was rendered")
	}
	if !strings.Contains(caddyfile.Content, "import /etc/caddy/snippets/gate-gates.caddy") {
		t.Errorf("the Caddyfile does not import the gate's named snippets:\n%s", caddyfile.Content)
	}
}

// Which gate an app sits behind is policy, and it is declared rather than
// implied by which snippet somebody remembered to import.
func TestTheGateIsDeclaredPerApp(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}
	caddyfile := files["vm/srv/infra/caddy/Caddyfile"].Content

	// talk sits behind the members gate in the fixture.
	if !strings.Contains(caddyfile, "import gate_members") {
		t.Errorf("a gated app's host block does not import its gate:\n%s", caddyfile)
	}

	// A Matrix client is not a browser and will not follow a redirect to a
	// passkey prompt, so chat and its apex must never be gated.
	for _, hostname := range []string{"chat.example.org", "example.org"} {
		block := hostBlock(t, caddyfile, hostname)
		if strings.Contains(block, "import gate_") {
			t.Errorf("%s is gated, which breaks every Matrix client:\n%s", hostname, block)
		}
	}
}

// Synapse is a resource server: MAS owns authentication, and Synapse must not
// carry a second way in. The single check that proves the split is that no
// oidc_providers block is rendered and the delegation to MAS is.
//
// The brief for this task asked for `msc3861` here, which is the experimental
// form. Synapse v1.160.0, the version this kind pins, documents the stable
// `matrix_authentication_service` block instead and its configuration manual
// no longer mentions msc3861 at all: checked against
// docs/usage/configuration/config_documentation.md at tag v1.160.0 on
// 2026-09-15. Asserting the experimental key would pin the toolkit to a shape
// the pinned image has moved past, so the stable one is asserted and the
// deviation is recorded in docs/decisions.md.
func TestSynapseDelegatesAuthenticationToMAS(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}

	homeserver := files["vm/srv/chat/homeserver.yaml"].Content
	if strings.Contains(homeserver, "oidc_providers") {
		t.Error("homeserver.yaml still configures its own OIDC, which is a second way in")
	}
	if strings.Contains(homeserver, "registration_shared_secret") {
		t.Error("registration_shared_secret is present, which bypasses MAS and the group restriction")
	}
	if !strings.Contains(homeserver, "matrix_authentication_service:") {
		t.Errorf("homeserver.yaml does not delegate to MAS:\n%s", homeserver)
	}

	mas, ok := files["vm/srv/chat/mas.yaml"]
	if !ok {
		t.Fatal("no MAS configuration was rendered")
	}
	if mas.Mode != 0o600 {
		t.Error("the MAS configuration carries secrets and must be 0600")
	}

	compose := files["vm/srv/chat/compose.yaml"].Content
	if !strings.Contains(compose, "mas:") {
		t.Error("the stack renders no MAS service")
	}
}

// Both sides of the shared secret have to be the same string, or Synapse and
// MAS each start cleanly and refuse every request between them.
func TestSynapseAndMASShareOneSecret(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}
	secret := "fixture-not-a-secret-chat-mas-matrix"
	for _, path := range []string{"vm/srv/chat/homeserver.yaml", "vm/srv/chat/mas.yaml"} {
		if !strings.Contains(files[path].Content, secret) {
			t.Errorf("%s does not carry the shared secret both sides need:\n%s", path, files[path].Content)
		}
	}
}

// MAS answers the three compatibility login paths, and if the /_matrix/* catch
// all captured them instead, every login would reach Synapse, which no longer
// knows how to answer one.
//
// What decides between them is matcher length, not the order they are written
// in: Caddy sorts routes of one directive longest matcher first, trailing
// wildcard trimmed (caddyconfig/httpcaddyfile/directives.go, sortRoutes, read
// at v2.11.4, the version this toolkit pins). An earlier version of this test
// asserted byte offsets in the rendered file and was named for order, which
// would not have caught the failure it named: the same snippet already writes
// /.well-known/matrix/* after both catch alls, and it wins anyway.
//
// This test asserts the property that governs, and only that. It reads
// rendered text, so it cannot observe what Caddy does with the sorted routes;
// proving that needs a running Caddy, which this suite does not have. The name
// says what is checked so that nobody reads a guarantee into it that is not
// here.
func TestTheLoginSplitOutranksTheCatchAllByMatcherLength(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}
	snippet, ok := files["vm/srv/infra/caddy/snippets/chat.caddy"]
	if !ok {
		t.Fatal("the homeserver has no snippet")
	}

	// matcherLength is what Caddy compares. It sorts routes of one directive
	// by path matcher length with a trailing wildcard trimmed, longest first.
	matcherLength := func(path string) int { return len(strings.TrimSuffix(path, "*")) }

	const catchAll = "/_matrix/*"
	if !strings.Contains(snippet.Content, "handle "+catchAll+" {") {
		t.Fatalf("the snippet has no %s catch all:\n%s", catchAll, snippet.Content)
	}
	for _, path := range []string{
		"/_matrix/client/*/login",
		"/_matrix/client/*/logout",
		"/_matrix/client/*/refresh",
	} {
		if !strings.Contains(snippet.Content, "handle "+path+" {") {
			t.Errorf("the snippet does not split %s off to MAS:\n%s", path, snippet.Content)
			continue
		}
		if matcherLength(path) <= matcherLength(catchAll) {
			t.Errorf("%s does not outrank %s on matcher length, so Caddy may sort the catch all ahead of it and Synapse answers the login",
				path, catchAll)
		}
	}
}

// The apex serves the delegation documents and nothing else. Routing it like
// the primary would publish the whole homeserver API there.
func TestTheApexServesOnlyDelegation(t *testing.T) {
	files := map[string]render.File{}
	for _, f := range build(t).Files {
		files[f.Path] = f
	}
	snippet, ok := files["vm/srv/infra/caddy/snippets/chat-wellknown.caddy"]
	if !ok {
		t.Fatal("the apex has no snippet")
	}
	if !strings.Contains(snippet.Content, "/.well-known/matrix/") {
		t.Errorf("the apex snippet does not serve the delegation documents:\n%s", snippet.Content)
	}
	if strings.Contains(snippet.Content, "/_matrix/") {
		t.Errorf("the apex snippet exposes the homeserver API:\n%s", snippet.Content)
	}
	// The name in every user identifier is the name the delegation is served
	// on, so that is what server_name has to be. If they disagree, the two
	// documents below point nowhere and federation resolves to the wrong host.
	homeserver := files["vm/srv/chat/homeserver.yaml"].Content
	if !strings.Contains(homeserver, `server_name: "example.org"`) {
		t.Errorf("server_name is not the name the delegation is served on:\n%s", homeserver)
	}
	for _, document := range []string{"/.well-known/matrix/server", "/.well-known/matrix/client"} {
		if !strings.Contains(snippet.Content, "handle "+document+" {") {
			t.Errorf("the apex does not answer %s:\n%s", document, snippet.Content)
		}
	}
}

// A homeserver that declares no delegation hostname answers the delegation
// documents itself, and the gateway has to send them to it.
//
// The fixture always declares one, so the golden tree never exercises this
// branch: a snippet that quietly routed /.well-known/matrix/* to MAS instead
// would render, review cleanly and leave a federating peer with a 404 that
// sends it to <server_name>:8448, where nothing listens.
func TestAHomeserverWithNoDelegationServesItsOwnWellKnown(t *testing.T) {
	cfg := fixture(t)
	secrets, err := config.LoadSecrets(filepath.Join("testdata", "secrets.fixture.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	chat := cfg.Apps["chat"]
	chat.Hostnames = nil
	cfg.Apps["chat"] = chat

	plan, err := render.Build(cfg, secrets)
	if err != nil {
		t.Fatalf("a homeserver with no delegation hostname failed to render: %v", err)
	}
	files := map[string]render.File{}
	for _, f := range plan.Files {
		files[f.Path] = f
	}

	if _, ok := files["vm/srv/infra/caddy/snippets/chat-wellknown.caddy"]; ok {
		t.Error("a snippet was rendered for a hostname role nobody declared")
	}

	homeserver := files["vm/srv/chat/homeserver.yaml"].Content
	if !strings.Contains(homeserver, "serve_server_wellknown: true") {
		t.Errorf("the homeserver was not told to serve its own delegation:\n%s", homeserver)
	}
	if !strings.Contains(homeserver, `server_name: "chat.example.org"`) {
		t.Errorf("server_name is not the only hostname this app has:\n%s", homeserver)
	}

	snippet := files["vm/srv/infra/caddy/snippets/chat.caddy"].Content
	at := strings.Index(snippet, "handle /.well-known/matrix/* {")
	if at < 0 {
		t.Fatalf("the gateway does not route the delegation documents anywhere:\n%s", snippet)
	}
	// Anywhere is not good enough: MAS does not serve them, and the bare
	// handle at the end of the snippet is MAS's.
	homeserverUpstream := "10.44.0.3:8008"
	rest := snippet[at:]
	end := strings.Index(rest, "\n}")
	if end < 0 {
		t.Fatalf("unterminated handle:\n%s", rest)
	}
	if !strings.Contains(rest[:end], homeserverUpstream) {
		t.Errorf("the delegation documents do not reach the homeserver:\n%s", rest[:end])
	}
}

// hostBlock returns the text of one host block, so a test can assert about one
// hostname rather than about the whole file.
func hostBlock(t *testing.T, caddyfile, hostname string) string {
	t.Helper()
	start := strings.Index(caddyfile, "\n"+hostname+" {")
	if start < 0 {
		t.Fatalf("no host block for %s", hostname)
	}
	end := strings.Index(caddyfile[start+1:], "\n}")
	if end < 0 {
		t.Fatalf("unterminated host block for %s", hostname)
	}
	return caddyfile[start : start+end]
}
